import type { ScreenDef } from '@core/world/screen';

export const nifIntHut: ScreenDef = {
  id: 'nif_int_hut',
  region: 'niflmyrr',
  purpose:
    "Hrafn the seal-hunter's turf hut: a hearth, a bed of skins, nets drying from the rafters and the smell of seal oil.",
  indoor: true,
  things: [
    { k: 'door', at: { x: 19, y: 15 }, dir: 's', to: 'nif_shore', arrive: { x: 19, y: 10 }, facing: 's' },
  ],
  map: [
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXwwwwwwwwwwwwXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXwbfffffffffwXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXwbfffffffffwXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXwffffhhffffwXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXwffffhhffffwXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXwffffffffffwXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXwffffffffffwXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXwfffffffttfwXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXwffffffffffwXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXwwwwwDwwwwwwXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  ],
};
