import type { ScreenDef } from '@core/world/screen';

export const askPasture: ScreenDef = {
  id: 'ask_pasture',
  region: 'askdalr',
  purpose:
    "The sheep meadow and its pen. Day 1: herd the five sheep through the gate on the pen's east side.",
  things: [
    { k: 'pen', at: { x: 5, y: 6 }, w: 9, h: 9, v: 'ask_pen', flag: 'q_sheep_d1', count: 5 },
    { k: 'critter', id: 'sheep', at: { x: 22, y: 8 }, tag: 0 },
    { k: 'critter', id: 'sheep', at: { x: 25, y: 11 }, tag: 1 },
    { k: 'critter', id: 'sheep', at: { x: 28, y: 7 }, tag: 2 },
    { k: 'critter', id: 'sheep', at: { x: 24, y: 14 }, tag: 3 },
    { k: 'critter', id: 'sheep', at: { x: 30, y: 12 }, tag: 4 },
  ],
  map: [
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'T......................................T',
    'T.T...........................T........T',
    'T.................""""""............T..T',
    'T.................""""""...............T',
    'T...===========...""""""...............T',
    'T...=.........=........................T',
    'T...=.........=........................T',
    'T...=..................................T',
    'T...=............................,,,,,,,',
    'T...=............................,,,,,,,',
    'T...=............................,,,,,,,',
    'T...=............................,,,,,,,',
    'T...=.........=........................T',
    'T...=.........=........................T',
    'T...===========..........."""""""".....T',
    'T........................."""""""".....T',
    'T...............""""""....""""""""...T.T',
    'T..T......T.....""""""...."""""""".....T',
    'T..............."""""".................T',
    'T......................................T',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  ],
};
