import type { ScreenDef } from '@core/world/screen';

export const askPasture: ScreenDef = {
  id: 'ask_pasture',
  region: 'askdalr',
  purpose:
    'The sheep meadow and its pen. Day 1: herd the five sheep west through the wide gate of the pen, which fills the west end of the meadow.',
  things: [
    { k: 'pen', at: { x: 1, y: 1 }, w: 11, h: 20, v: 'ask_pen', flag: 'q_sheep_d1', count: 5 },
    { k: 'critter', id: 'sheep', at: { x: 22, y: 8 }, tag: 0 },
    { k: 'critter', id: 'sheep', at: { x: 25, y: 11 }, tag: 1 },
    { k: 'critter', id: 'sheep', at: { x: 28, y: 7 }, tag: 2 },
    { k: 'critter', id: 'sheep', at: { x: 24, y: 14 }, tag: 3 },
    { k: 'critter', id: 'sheep', at: { x: 30, y: 12 }, tag: 4 },
  ],
  map: [
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'T...........=..........................T',
    'T...........=.................T........T',
    'T...T.......=.....""""""............T..T',
    'T...........=.....""""""...............T',
    'T...........=.....""""""...............T',
    'T...........=..........................T',
    'T...........=..........................T',
    'T......................................T',
    'T................................,,,,,,,',
    'T................................,,,,,,,',
    'T................................,,,,,,,',
    'T................................,,,,,,,',
    'T......................................T',
    'T...........=..........................T',
    'T...........=............."""""""".....T',
    'T...........=............."""""""".....T',
    'T........T..=...""""""....""""""""...T.T',
    'T...........=...""""""...."""""""".....T',
    'T...........=..."""""".................T',
    'T...........=..........................T',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  ],
};
