import type { ScreenDef } from '@core/world/screen';

export const askIntLonghouse: ScreenDef = {
  id: 'ask_int_longhouse',
  region: 'askdalr',
  purpose: "Halvar's longhouse, where Ask sleeps. The prologue starts and ends each day at Ask's bed.",
  indoor: true,
  things: [
    { k: 'door', at: { x: 19, y: 20 }, dir: 's', to: 'ask_farmyard', arrive: { x: 9, y: 8 }, facing: 's' },
  ],
  map: [
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXwwwwwwwwwwwwwwwwwwwwwwwwwwXXXXXXX',
    'XXXXXXXwffffffffffffffffffffffffwXXXXXXX',
    'XXXXXXXwffffffffffffffffffffffffwXXXXXXX',
    'XXXXXXXwffbffffffffffffffffbfbffwXXXXXXX',
    'XXXXXXXwffffffffffffffffffffffffwXXXXXXX',
    'XXXXXXXwffffffffffffffffffffffffwXXXXXXX',
    'XXXXXXXwffffffffffffffffffffffffwXXXXXXX',
    'XXXXXXXwffffffffffhhhhffffffffffwXXXXXXX',
    'XXXXXXXwffffffffffffffffffffffffwXXXXXXX',
    'XXXXXXXwffffffffffffffffffffffffwXXXXXXX',
    'XXXXXXXwffffffffffffffffffffffffwXXXXXXX',
    'XXXXXXXwffffffffffffffffffttffffwXXXXXXX',
    'XXXXXXXwfftfffffffffffffffffffffwXXXXXXX',
    'XXXXXXXwffffffffffffffffffffffffwXXXXXXX',
    'XXXXXXXwffffffffffffffffffffffffwXXXXXXX',
    'XXXXXXXwffffffffffffffffffffffffwXXXXXXX',
    'XXXXXXXwwwwwwwwwwwwDwwwwwwwwwwwwwXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  ],
};
