import type { ScreenDef } from '@core/world/screen';

export const d7R04: ScreenDef = {
  id: 'd7_r04',
  region: 'hrimfjoll',
  dungeon: 'd7',
  purpose:
    "Hrímgerðr's hall: she stands at its north end (20, 4) and casts. The great door slams until she falls; then the heart container, the captives' chains break, Kolbeinn speaks, and the rune-stone (20, 2) takes Ask out to the tower's foot. Two pillars (21, 16) and (19, 13) stop a slide in her line once she glazes the floor.",
  things: [
    { k: 'lock', id: 'd7_lock_big', at: { x: 19, y: 21 }, w: 2, h: 1, big: true },
    {
      k: 'shutter',
      at: { x: 19, y: 21 },
      w: 2,
      h: 1,
      opens: 'clear',
      when: { k: 'not', c: { k: 'flag', id: 'st_d7_boss_dead' } },
    },
    {
      k: 'enemy',
      id: 'hrimgerdr',
      at: { x: 20, y: 4 },
      when: { k: 'not', c: { k: 'flag', id: 'st_d7_boss_dead' } },
      onDeath: [
        { k: 'set', flag: 'st_d7_boss_dead', value: true },
        { k: 'set', flag: 'st_thane_hrimgerdr', value: true },
        { k: 'add', flag: 'q_thanes', n: 1 },
        { k: 'set', flag: 'st_freed_asa', value: true },
        { k: 'set', flag: 'st_freed_bjarni', value: true },
        { k: 'add', flag: 'q_captives', n: 2 },
      ],
    },
    { k: 'heart', id: 'd7_hc', at: { x: 20, y: 10 }, when: { k: 'flag', id: 'st_d7_boss_dead' } },
    {
      k: 'trigger',
      at: { x: 14, y: 4 },
      w: 12,
      h: 2,
      script: 'd7_kolbeinn',
      when: {
        k: 'all',
        of: [
          { k: 'flag', id: 'st_d7_boss_dead' },
          { k: 'not', c: { k: 'flag', id: 'st_d7_kolbeinn' } },
        ],
      },
    },
    { k: 'use', at: { x: 20, y: 2 }, script: 'd7_gate_out', when: { k: 'flag', id: 'st_d7_boss_dead' } },
  ],
  map: [
    '▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪',
    '▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫Y▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▫▫▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪',
    '▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▫▫▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪',
  ],
};
