import type { ScreenDef } from '@core/world/screen';

export const d7R23: ScreenDef = {
  id: 'd7_r23',
  region: 'hrimfjoll',
  dungeon: 'd7',
  purpose:
    "The mirror's hall, safe: the ice mirror in a chest (20, 10), and a basin of meltwater (10, 2) that makes Ask whole. A window (30, 2) shines a beam south down the hall; the crystal eye (36, 13) sits in its niche off to the side, where no beam goes alone. Ask stands in the beam with the mirror raised, facing east, and the bars on the east door (37, 10) lift.",
  things: [
    { k: 'chest', id: 'd7_c_mirror', at: { x: 20, y: 10 }, gives: { item: 'mirror' } },
    { k: 'use', at: { x: 10, y: 2 }, w: 3, script: 'd7_basin' },
    { k: 'beam', at: { x: 30, y: 2 }, dir: 's' },
    { k: 'eye', at: { x: 36, y: 13 }, flag: 'st_d7_eye_r23' },
    {
      k: 'gate',
      at: { x: 37, y: 10 },
      w: 1,
      h: 2,
      art: 'bars',
      closed: { k: 'not', c: { k: 'flag', id: 'st_d7_eye_r23' } },
    },
    {
      k: 'sign',
      at: { x: 24, y: 2 },
      text: {
        en: 'Scratched in the rime by a small hand: STAND IN THE LIGHT AND TURN IT.',
        sv: 'Ristat i rimfrosten av en liten hand: STÅ I LJUSET OCH VÄND DET.',
      },
    },
  ],
  map: [
    '▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪',
    '▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪',
    '▪▪▫▫▫▫▫▫▫▫UUU▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫',
    '▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪▪▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▧▫▪▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪▪▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▫▪▪',
    '▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪',
    '▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪',
  ],
};
