import type { ScreenDef } from '@core/world/screen';

export const d2R13: ScreenDef = {
  id: 'd2_r13',
  region: 'myrland',
  dungeon: 'd2',
  water: 'w_d2_level',
  purpose:
    'The piece of heart, a combination: drain the water, walk the high sluice to a cracked wall, bomb it, boomerang the level-2 wheel from the nook behind, and the planks rise to the islet. A wheel in reach of each landing sets the water back.',
  things: [
    { k: 'wheel', at: { x: 24, y: 18 }, level: 0 },
    { k: 'wheel', at: { x: 22, y: 12 }, level: 2 },
    { k: 'wheel', at: { x: 13, y: 7 }, level: 2 },
    { k: 'wheel', at: { x: 4, y: 4 }, level: 0 },
    { k: 'crack', id: 'd2_k_r13', at: { x: 8, y: 6 }, w: 2, h: 1, art: 'wall' },
    { k: 'piece', id: 'hp_d2_r13', at: { x: 31, y: 5 } },
    { k: 'prop', id: 'bomb_pot', at: { x: 16, y: 18 } },
    { k: 'prop', id: 'bomb_pot', at: { x: 17, y: 18 } },
  ],
  map: [
    'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
    'HH~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~HH',
    'HH~~~~FFFFFF4444444444444444FFFFFF~~~~HH',
    'HH~~~~FFFFFF4444444444444444FFFFFF~~~~HH',
    'HH~~~~FFFFFF~~~~~~~~~~~~~~~~FFFFFF~~~~HH',
    'HH~~~~HHFFHH~~~~~~~~~~~~~~~~FFFFFF~~~~HH',
    'HH~~~~~~22~~~~~~~~~~~~~~~~~~FFFFFF~~~~HH',
    'HH~~~~~~22~~~~~~~~~~~~~~~~~~FFFFFF~~~~HH',
    'HH~~~~~~22~~~~~~~~~~~~~~~~~~~~~~~~~~~~HH',
    'HH~~~~~~22~~~~~~~~~~~~~~~~~~~~~~~~~~~~HH',
    'HH~~~~~~22~~~~~~~~~~~~~~~~~~~~~~~~~~~~HH',
    'HH~~~~~~22~~~~~~~~~~~~~~~~~~~~~~~~~~~~HH',
    'HH~~~~~~22~~~~~~~~~~~~~~~~~~~~~~~~~~~~HH',
    'HH~~~~~~22~~~~~~~~~~~~~~~~~~~~~~~~~~~~HH',
    'HH~~~~~~222222FFFFFFFFFFFFFFFFFFFF~~~~HH',
    'HH~~~~~~222222FFFFFFFFFFFFFFFFFFFF~~~~HH',
    'HH~~~~~~~~~~~~FFFFFFFFFFFFFFFFFFFF~~~~HH',
    'HH~~~~~~~~~~~~FFFFFFFFFFFFFFFFFFFF~~~~HH',
    'HH~~~~~~~~~~~~FFFFFFFFFFFFFFFFFFFF~~~~HH',
    'HHHHHHHHHHHHHHHHHHH44HHHHHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHHHHH44HHHHHHHHHHHHHHHHHHH',
  ],
};
