import type { ScreenDef } from '@core/world/screen';

export const d2R11: ScreenDef = {
  id: 'd2_r11',
  region: 'myrland',
  dungeon: 'd2',
  water: 'w_d2_level',
  purpose:
    "The big key's room, behind lock C: beat the draugr and the mud-crab and the big key appears. The big lock north is Lindormr's door.",
  things: [
    { k: 'lock', id: 'd2_lock_c', at: { x: 39, y: 10 }, w: 1, h: 2 },
    { k: 'lock', id: 'd2_lock_big', at: { x: 19, y: 0 }, w: 2, h: 1, big: true },
    { k: 'enemy', id: 'draugr', at: { x: 12, y: 10 } },
    { k: 'enemy', id: 'draugr', at: { x: 28, y: 10 } },
    { k: 'enemy', id: 'leirkrabbi', at: { x: 20, y: 14 } },
    { k: 'chest', id: 'd2_c_bigkey', at: { x: 20, y: 6 }, gives: { item: 'big_key' }, appear: 'clear' },
    { k: 'prop', id: 'bomb_pot', at: { x: 34, y: 18 } },
    { k: 'prop', id: 'bomb_pot', at: { x: 35, y: 18 } },
  ],
  map: [
    'HHHHHHHHHHHHHHHHHHHFFHHHHHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHHHHHFFHHHHHHHHHHHHHHHHHHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFHHHFFFFFFFFFFFFFFFFFFFFFFHHHFFFFHH',
    'HHFFFFHHHFFFFFFFFFFFFFFFFFFFFFFHHHFFFFHH',
    'HHFFFFHHHFFFFFFFFFFFFFFFFFFFFFFHHHFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFHHHFFFFFFFFFFFFFFFFFFFFFFHHHFFFFHH',
    'HHFFFFHHHFFFFFFFFFFFFFFFFFFFFFFHHHFFFFHH',
    'HHFFFFHHHFFFFFFFFFFFFFFFFFFFFFFHHHFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
  ],
};
