import type { ScreenDef } from '@core/world/screen';

export const d2R08: ScreenDef = {
  id: 'd2_r08',
  region: 'myrland',
  dungeon: 'd2',
  water: 'w_d2_level',
  purpose:
    'The crab pen: two mud-crabs guard key 3 and only bombs crack their shells. Bomb pots by the door; a cracked wall south is a shortcut to the sump.',
  things: [
    { k: 'shutter', id: 'd2_sh_r07', at: { x: 0, y: 10 }, w: 1, h: 2 },
    { k: 'enemy', id: 'leirkrabbi', at: { x: 28, y: 6 } },
    { k: 'enemy', id: 'leirkrabbi', at: { x: 32, y: 7 } },
    { k: 'chest', id: 'd2_c_key3', at: { x: 30, y: 5 }, gives: { item: 'small_key' }, appear: 'clear' },
    { k: 'crack', id: 'd2_k_r04', at: { x: 19, y: 21 }, w: 2, h: 1, art: 'wall' },
    { k: 'prop', id: 'bomb_pot', at: { x: 4, y: 4 } },
    { k: 'prop', id: 'bomb_pot', at: { x: 4, y: 5 } },
    { k: 'prop', id: 'bomb_pot', at: { x: 16, y: 18 } },
    { k: 'prop', id: 'bomb_pot', at: { x: 23, y: 18 } },
  ],
  map: [
    'HHHHHHHHHHHHHHHHHHHFFHHHHHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHHHHHFFHHHHHHHHHHHHHHHHHHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFHHHHHHHHHHHHFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFHH',
    'FFFFFFFFFFFFFFFFFFFFFFFFHHHHFFFHHHHHFFHH',
    'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHHHHHHHHHHHHHHHHHHFFHHHHHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHHHHHFFHHHHHHHHHHHHHHHHHHH',
  ],
};
