import type { ScreenDef } from '@core/world/screen';

export const d2R03: ScreenDef = {
  id: 'd2_r03',
  region: 'myrland',
  dungeon: 'd2',
  water: 'w_d2_level',
  purpose:
    'The cellar, reached over the sluice floor while the water is low: drained channels between the piers, two draugr, and the map.',
  things: [
    { k: 'chest', id: 'd2_c_map', at: { x: 4, y: 4 }, gives: { item: 'dungeon_map' } },
    { k: 'enemy', id: 'draugr', at: { x: 18, y: 17 } },
    { k: 'enemy', id: 'draugr', at: { x: 30, y: 5 } },
  ],
  map: [
    'HHHHHHHHHHHHHHHHHHHFFHHHHHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHHHHHFFHHHHHHHHHHHHHHHHHHH',
    'HHFFFFFF111FFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFF111HHHHHFFFFFFHHHHFFFFFFFFFFFFHH',
    'HHFFFFFF111HHHHHFFFFFFHHHHFFFFFFFFFFFFHH',
    'HHFFFFFF111HHHHHFFFFFFHHHHFFFFFFFFFFFFHH',
    'HHFFFFFF111HHHHHFFFFFFHHHHFFFFFFFFFFFFHH',
    'HHFFFFFF111HHHHHFFFFFFHHHHFFFFFFFFFFFFHH',
    'HHFFFFFF111HHHHHFFFFFFHHHHFFFFFFFFFFFFHH',
    'HHFFFFFF111HHHHHFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFF111HHHHHFFFFFFFFFFFF111111111111',
    'HHFFFFFF111HHHHHFFFFFFFFFFFF111111111111',
    'HHFFFFFF111FFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HH11111111111111111111111111FFFFFFFFFFHH',
    'HH11111111111111111111111111FFFFFFFFFFHH',
    'HH11111111111111111111111111FFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
  ],
};
