import type { ScreenDef } from '@core/world/screen';

export const d2R15: ScreenDef = {
  id: 'd2_r15',
  region: 'myrland',
  dungeon: 'd2',
  water: 'w_d2_level',
  purpose:
    "Lindormr's pond at the bottom of the mill: silt round four mud mounds. The door slams until the serpent dies; then a heart container, and the shutter east opens to the stone.",
  things: [
    { k: 'lock', id: 'd2_lock_big', at: { x: 19, y: 21 }, w: 2, h: 1, big: true },
    {
      k: 'shutter',
      at: { x: 19, y: 20 },
      w: 2,
      h: 1,
      opens: 'clear',
      when: { k: 'not', c: { k: 'flag', id: 'st_d2_boss_dead' } },
    },
    { k: 'shutter', id: 'd2_sh_r16', at: { x: 39, y: 10 }, w: 1, h: 2, opens: 'clear' },
    {
      k: 'enemy',
      id: 'lindormr',
      at: { x: 20, y: 10 },
      when: { k: 'not', c: { k: 'flag', id: 'st_d2_boss_dead' } },
      onDeath: [{ k: 'set', flag: 'st_d2_boss_dead', value: true }],
    },
    { k: 'heart', id: 'd2_hc', at: { x: 20, y: 16 }, when: { k: 'flag', id: 'st_d2_boss_dead' } },
    { k: 'prop', id: 'bomb_pot', at: { x: 17, y: 18 } },
    { k: 'prop', id: 'bomb_pot', at: { x: 22, y: 18 } },
  ],
  map: [
    'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
    'HH~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~HH',
    'HH~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~HH',
    'HH~~llllllllllllllllllllllllllllllll~~HH',
    'HH~~llllllllllllllllllllllllllllllll~~HH',
    'HH~~llllllllllllllllllllllllllllllll~~HH',
    'HH~~llllllllllllllllllllllllllllllll~~HH',
    'HH~~llllllllllllllllllllllllllllllll~~HH',
    'HH~~llllllllllllllllllllllllllllllll~~HH',
    'HH~~llllllllllllllllllllllllllllllllllll',
    'HH~~llllllllllllllllllllllllllllllllllll',
    'HH~~llllllllllllllllllllllllllllllll~~HH',
    'HH~~llllllllllllllllllllllllllllllll~~HH',
    'HH~~llllllllllllllllllllllllllllllll~~HH',
    'HH~~llllllllllllllllllllllllllllllll~~HH',
    'HH~~llllllllllllllllllllllllllllllll~~HH',
    'HH~~llllllllllllllllllllllllllllllll~~HH',
    'HH~~lllllllllllllFFFFFFlllllllllllll~~HH',
    'HH~~lllllllllllllFFFFFFlllllllllllll~~HH',
    'HHHHHHHHHHHHHHHHHHHFFHHHHHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHHHHHFFHHHHHHHHHHHHHHHHHHH',
  ],
};
