import type { ScreenDef } from '@core/world/screen';

export const d2R07: ScreenDef = {
  id: 'd2_r07',
  region: 'myrland',
  dungeon: 'd2',
  water: 'w_d2_level',
  purpose:
    'The powder store. The doors slam behind Ask; once the draugr fall, the bombs appear. Bomb pots line the walls, and a cracked stretch of the south wall opens onto a ledge down into the mill-race.',
  things: [
    { k: 'lock', id: 'd2_lock_a', at: { x: 0, y: 10 }, w: 1, h: 2 },
    { k: 'shutter', id: 'd2_sh_r07w', at: { x: 1, y: 10 }, w: 1, h: 2, opens: 'clear' },
    { k: 'shutter', id: 'd2_sh_r07', at: { x: 39, y: 10 }, w: 1, h: 2, opens: 'clear' },
    { k: 'enemy', id: 'draugr', at: { x: 12, y: 6 } },
    { k: 'enemy', id: 'draugr', at: { x: 28, y: 13 } },
    { k: 'chest', id: 'd2_c_bombs', at: { x: 20, y: 6 }, gives: { item: 'bombs', n: 10 }, appear: 'clear' },
    { k: 'crack', id: 'd2_k_r07', at: { x: 19, y: 16 }, w: 2, h: 1, art: 'wall' },
    { k: 'prop', id: 'bomb_pot', at: { x: 4, y: 3 } },
    { k: 'prop', id: 'bomb_pot', at: { x: 5, y: 3 } },
    { k: 'prop', id: 'bomb_pot', at: { x: 34, y: 3 } },
    { k: 'prop', id: 'bomb_pot', at: { x: 35, y: 3 } },
    { k: 'prop', id: 'bomb_pot', at: { x: 16, y: 14 } },
    { k: 'prop', id: 'bomb_pot', at: { x: 23, y: 14 } },
  ],
  map: [
    'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
    'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHHHHHHHHHHHHHHHHHHFFHHHHHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHHHHHFFHHHHHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHHHHHFFHHHHHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHHHHH__HHHHHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHHHHHFFHHHHHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHHHHHFFHHHHHHHHHHHHHHHHHHH',
  ],
};
