import type { ScreenDef } from '@core/world/screen';

export const d2R01: ScreenDef = {
  id: 'd2_r01',
  region: 'myrland',
  dungeon: 'd2',
  water: 'w_d2_level',
  purpose:
    'The wheel-house, just inside the mill door and safe. Two wheels on the landing set the water as found (0) or up to the race planks (1): dry, the sluice floor west leads to the cellar; high, the planks east float to the mill-race. North is the millstone hall.',
  things: [
    { k: 'door', at: { x: 19, y: 20 }, dir: 's', to: 'myl_mill', arrive: { x: 18, y: 15 }, facing: 's' },
    { k: 'door', at: { x: 20, y: 20 }, dir: 's', to: 'myl_mill', arrive: { x: 19, y: 15 }, facing: 's' },
    {
      k: 'trigger',
      at: { x: 14, y: 14 },
      w: 12,
      h: 5,
      script: 'd2_enter',
      when: { k: 'not', c: { k: 'flag', id: 'st_d2_entered' } },
    },
    { k: 'wheel', at: { x: 14, y: 6 }, level: 0 },
    { k: 'wheel', at: { x: 25, y: 6 }, level: 1 },
    { k: 'prop', id: 'pot', at: { x: 13, y: 18 } },
    { k: 'prop', id: 'pot', at: { x: 26, y: 18 } },
  ],
  map: [
    'HHHHHHHHHHHHHHHHHHHFFHHHHHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHHHHHFFHHHHHHHHHHHHHHHHHHH',
    'HH~~~~~~~~~~FFFFFFFFFFFFFFFF~~~~~~~~~~HH',
    'HH~~~~~~~~~~FFFFFFFFFFFFFFFF~~~~~~~~~~HH',
    'HH~~~~~~~~~~FFFFFFFFFFFFFFFF~~~~~~~~~~HH',
    'HH~~~~~~~~~~FFFFFFFFFFFFFFFF~~~~~~~~~~HH',
    'HH~~~~~~~~~~FFFFFFFFFFFFFFFF~~~~~~~~~~HH',
    'HH~~~~~~~~~~FFFFFFFFFFFFFFFF~~~~~~~~~~HH',
    'HH~~~~~~~~~~FFFFFFFFFFFFFFFF~~~~~~~~~~HH',
    'HH~~~~~~~~~~FFFFFFFFFFFFFFFF~~~~~~~~~~HH',
    '111111111111FFFFFFFFFFFFFFFF333333333333',
    '111111111111FFFFFFFFFFFFFFFF333333333333',
    'HH~~~~~~~~~~FFFFFFFFFFFFFFFF~~~~~~~~~~HH',
    'HH~~~~~~~~~~FFFFFFFFFFFFFFFF~~~~~~~~~~HH',
    'HH~~~~~~~~~~FFFFFFFFFFFFFFFF~~~~~~~~~~HH',
    'HH~~~~~~~~~~FFFFFFFFFFFFFFFF~~~~~~~~~~HH',
    'HH~~~~~~~~~~FFFFFFFFFFFFFFFF~~~~~~~~~~HH',
    'HH~~~~~~~~~~FFFFFFFFFFFFFFFF~~~~~~~~~~HH',
    'HH~~~~~~~~~~FFFFFFFFFFFFFFFF~~~~~~~~~~HH',
    'HH~~~~~~~~~~FFFFFFFFFFFFFFFF~~~~~~~~~~HH',
    'HHHHHHHHHHHHHHHHHHHFFHHHHHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
  ],
};
