import type { ScreenDef } from '@core/world/screen';

export const d2R16: ScreenDef = {
  id: 'd2_r16',
  region: 'myrland',
  dungeon: 'd2',
  water: 'w_d2_level',
  purpose: "The second runestone, in the mill's deepest cellar.",
  things: [
    { k: 'shutter', id: 'd2_sh_r16', at: { x: 0, y: 10 }, w: 1, h: 2 },
    {
      k: 'use',
      at: { x: 20, y: 4 },
      script: 'stone2_light',
      when: {
        k: 'all',
        of: [
          { k: 'flag', id: 'st_d2_boss_dead' },
          { k: 'not', c: { k: 'flag', id: 'st_stone2_lit' } },
        ],
      },
    },
  ],
  map: [
    'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFYFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHH',
    'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
  ],
};
