import type { TerrainId } from '../terrain';

/** One character per terrain in screen text maps. */
export const LEGEND: Readonly<Record<string, TerrainId>> = {
  '.': 'grass',
  ',': 'path',
  '~': 'water',
  '#': 'rock',
  T: 'tree',
  _: 'ledge',
  '=': 'fence',
  ':': 'field',
  ';': 'yard',
  R: 'roof',
  W: 'wall',
  D: 'door',
  f: 'floor',
  w: 'wall_int',
  X: 'void',
  o: 'ford',
  O: 'well',
  U: 'trough',
  S: 'stump',
  b: 'bed',
  h: 'hearth',
  t: 'table',
  M: 'menhir',
  d: 'door_shut',
  '+': 'window',
  C: 'chimney',
  J: 'jetty',
  P: 'pine',
  L: 'log',
  m: 'mound',
  k: 'kiln',
  c: 'cave_floor',
  Q: 'cave_wall',
  z: 'sap',
  r: 'roots',
  Y: 'runestone',
  V: 'cave_mouth',
  p: 'planks',
  I: 'palisade',
  n: 'sand',
  x: 'stall',
  G: 'thingstone',
  a: 'anvil',
  g: 'bog',
  y: 'reeds',
  B: 'birch',
  u: 'moss',
  K: 'boulder',
  v: 'rapids',
  s: 'spring',
  e: 'shoal',
  q: 'peat',
  Z: 'mill',
  A: 'boat',
  /** Sökkva Kvern's rising water: sluice floors that flood (1, 2) and race planks that float (3, 4). */
  '1': 'sluice',
  '2': 'sluice_hi',
  '3': 'race',
  '4': 'race_hi',
  F: 'boards',
  H: 'mill_wall',
  l: 'silt',
  /** Haugar (M4a). */
  E: 'heath',
  N: 'barrow',
  i: 'cairn',
  j: 'flagstone',
  $: 'drystone',
  '&': 'tent',
  /** Konungshaugr (M4b): floor, walls, pits and the hidden floor over them. */
  '7': 'crypt_floor',
  '8': 'crypt_wall',
  '0': 'pit',
  '9': 'ghost',
  /** Niflmýrr (M6a): black pools that never freeze, dead trees and the sedge mire. */
  '5': 'blackwater',
  '6': 'snag',
  '*': 'mire',
  '-': 'drowned_path',
  /** Sævatn (M7a): currents (north, east, south, west) and surges. */
  '/': 'current_n',
  '>': 'current_e',
  '|': 'current_s',
  '<': 'current_w',
  '[': 'surge_n',
  '}': 'surge_e',
  ']': 'surge_s',
  '{': 'surge_w',
  '@': 'hof_floor',
  '!': 'hof_floor_hi',
  '(': 'arch',
  /** Dvergagröf and Ívaldi's Forge (M8): scree, forge floor and wall, lava, and belts by the way they run. */
  '·': 'scree',
  '░': 'forge_floor',
  '▓': 'forge_wall',
  '≈': 'lava',
  '↑': 'belt_n',
  '→': 'belt_e',
  '↓': 'belt_s',
  '←': 'belt_w',
  /** Hrímfjöll and Hrímturn (M9): firn, glaze, rime cliffs, and the tower's floor and walls. */
  '∴': 'firn',
  '◇': 'glaze',
  '▒': 'rime',
  '▫': 'tower_floor',
  '▪': 'tower_wall',
  '▧': 'clear_ice',
  /** Grass under tall grass cover (see COVER_LEGEND). */
  '"': 'grass',
  '%': 'grass',
  /** Grass under a winter drift. */
  '^': 'grass',
};
