import type { TerrainId } from '../terrain';

/** One character per terrain in screen text maps. */
export const LEGEND: Readonly<Record<string, TerrainId>> = {
  '.': 'grass',
  ',': 'path',
  '~': 'water',
  '#': 'rock',
  T: 'tree',
  _: 'ledge',
  '=': 'fence',
  ':': 'field',
  ';': 'yard',
  R: 'roof',
  W: 'wall',
  D: 'door',
  f: 'floor',
  w: 'wall_int',
  X: 'void',
  o: 'ford',
  O: 'well',
  U: 'trough',
  S: 'stump',
  b: 'bed',
  h: 'hearth',
  t: 'table',
  M: 'menhir',
  d: 'door_shut',
  '+': 'window',
  C: 'chimney',
  J: 'jetty',
  P: 'pine',
  L: 'log',
  m: 'mound',
  k: 'kiln',
  c: 'cave_floor',
  Q: 'cave_wall',
  z: 'sap',
  r: 'roots',
  Y: 'runestone',
  V: 'cave_mouth',
  /** Grass under tall grass cover (see COVER_LEGEND). */
  '"': 'grass',
  '%': 'grass',
};
