import type { TerrainId } from '../terrain';

/** One character per terrain in screen text maps. */
export const LEGEND: Readonly<Record<string, TerrainId>> = {
  '.': 'grass',
  ',': 'path',
  '~': 'water',
  '#': 'rock',
  T: 'tree',
  _: 'ledge',
  '=': 'fence',
  ':': 'field',
  ';': 'yard',
  R: 'roof',
  W: 'wall',
  D: 'door',
  f: 'floor',
  w: 'wall_int',
  X: 'void',
  o: 'ford',
  O: 'well',
  U: 'trough',
  S: 'stump',
  b: 'bed',
  h: 'hearth',
  t: 'table',
  M: 'menhir',
  d: 'door_shut',
  '+': 'window',
  C: 'chimney',
  J: 'jetty',
  P: 'pine',
  L: 'log',
  m: 'mound',
  k: 'kiln',
  c: 'cave_floor',
  Q: 'cave_wall',
  z: 'sap',
  r: 'roots',
  Y: 'runestone',
  V: 'cave_mouth',
  p: 'planks',
  I: 'palisade',
  n: 'sand',
  x: 'stall',
  G: 'thingstone',
  a: 'anvil',
  g: 'bog',
  y: 'reeds',
  B: 'birch',
  u: 'moss',
  K: 'boulder',
  v: 'rapids',
  s: 'spring',
  e: 'shoal',
  q: 'peat',
  Z: 'mill',
  A: 'boat',
  /** Sökkva Kvern's rising water: sluice floors that flood (1, 2) and race planks that float (3, 4). */
  '1': 'sluice',
  '2': 'sluice_hi',
  '3': 'race',
  '4': 'race_hi',
  F: 'boards',
  H: 'mill_wall',
  l: 'silt',
  /** Grass under tall grass cover (see COVER_LEGEND). */
  '"': 'grass',
  '%': 'grass',
  /** Grass under a winter drift. */
  '^': 'grass',
};
