/** Every screen id. Add the id here, the ScreenDef in its region folder, and the entry in registry.ts. */
export const SCREEN_IDS = [
  'test_a',
  'test_b',
  'test_c',
  'test_int',
  'ask_farmyard',
  'ask_pasture',
  'ask_field',
  'ask_brook',
  'ask_village',
  'ask_hof',
  'ask_gate',
  'ask_ridge',
  'ask_int_longhouse',
  'ask_int_trader',
  'ask_int_hof',
  'myr_road_s',
  'myr_road',
  'myr_deep',
  'myr_brook',
  'myr_clearing',
  'myr_hollow',
  'myr_pines',
  'myr_charcoal',
  'myr_roots',
  'myr_int_hut',
  'myr_north',
  'myr_fen',
  'myr_int_volva',
  'myr_glade',
  'myr_trollskog',
  'upp_gate',
  'upp_square',
  'upp_hall',
  'upp_smiths',
  'upp_int_meadhall',
  'upp_int_trader',
  'upp_int_smithy',
  'upp_int_runehall',
  'upp_int_hof',
  'd1_r01',
  'd1_r02',
  'd1_r03',
  'd1_r04',
  'd1_r05',
  'd1_r06',
  'd1_r07',
  'd1_r08',
  'd1_r09',
  'd1_r10',
  'd1_r11',
  'd1_r12',
] as const;
export type ScreenId = (typeof SCREEN_IDS)[number];

export const isScreenId = (s: string): s is ScreenId => (SCREEN_IDS as readonly string[]).includes(s);
