import type { ScreenDef } from '@core/world/screen';

export const d6R04: ScreenDef = {
  id: 'd6_r04',
  region: 'dvergagrof',
  dungeon: 'd6',
  purpose:
    "Ívaldi's hall: the anvil throne. The great door slams until Ívaldi falls; then the heart container, the captives' chains break, Kolbeinn speaks, and the rune-stone (20, 3) takes Ask out to the forge gate.",
  things: [
    { k: 'lock', id: 'd6_lock_big', at: { x: 19, y: 21 }, w: 2, h: 1, big: true },
    {
      k: 'shutter',
      at: { x: 19, y: 21 },
      w: 2,
      h: 1,
      opens: 'clear',
      when: { k: 'not', c: { k: 'flag', id: 'st_d6_boss_dead' } },
    },
    {
      k: 'enemy',
      id: 'ivaldi',
      at: { x: 20, y: 10 },
      when: { k: 'not', c: { k: 'flag', id: 'st_d6_boss_dead' } },
      onDeath: [
        { k: 'set', flag: 'st_d6_boss_dead', value: true },
        { k: 'set', flag: 'st_thane_ivaldi', value: true },
        { k: 'add', flag: 'q_thanes', n: 1 },
        { k: 'set', flag: 'st_freed_thorkell', value: true },
        { k: 'set', flag: 'st_freed_rannveig', value: true },
        { k: 'add', flag: 'q_captives', n: 2 },
      ],
    },
    { k: 'heart', id: 'd6_hc', at: { x: 20, y: 12 }, when: { k: 'flag', id: 'st_d6_boss_dead' } },
    {
      k: 'trigger',
      at: { x: 14, y: 4 },
      w: 12,
      h: 2,
      script: 'd6_kolbeinn',
      when: {
        k: 'all',
        of: [
          { k: 'flag', id: 'st_d6_boss_dead' },
          { k: 'not', c: { k: 'flag', id: 'st_d6_kolbeinn' } },
        ],
      },
    },
    { k: 'use', at: { x: 20, y: 3 }, script: 'd6_gate_out', when: { k: 'flag', id: 'st_d6_boss_dead' } },
    { k: 'brazier', at: { x: 8, y: 3 }, lit: true },
    { k: 'brazier', at: { x: 31, y: 3 }, lit: true },
    { k: 'brazier', at: { x: 8, y: 18 }, lit: true },
    { k: 'brazier', at: { x: 31, y: 18 }, lit: true },
  ],
  map: [
    '▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓',
    '▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓',
    '▓▓≈≈░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░≈≈▓▓',
    '▓▓≈≈░░░░░░░░░░░░░░░░Y░░░░░░░░░░░░░░░≈≈▓▓',
    '▓▓≈≈░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░≈≈▓▓',
    '▓▓≈≈░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░≈≈▓▓',
    '▓▓≈≈░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░≈≈▓▓',
    '▓▓≈≈░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░≈≈▓▓',
    '▓▓≈≈░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░≈≈▓▓',
    '▓▓≈≈░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░≈≈▓▓',
    '▓▓≈≈░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░≈≈▓▓',
    '▓▓≈≈░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░≈≈▓▓',
    '▓▓≈≈░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░≈≈▓▓',
    '▓▓≈≈░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░≈≈▓▓',
    '▓▓≈≈░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░≈≈▓▓',
    '▓▓≈≈░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░≈≈▓▓',
    '▓▓≈≈░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░≈≈▓▓',
    '▓▓≈≈░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░≈≈▓▓',
    '▓▓≈≈░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░≈≈▓▓',
    '▓▓≈≈░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░≈≈▓▓',
    '▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓',
    '▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓',
  ],
};
