import type { ScreenDef } from '@core/world/screen';

export const mylIntCave: ScreenDef = {
  id: 'myl_int_cave',
  region: 'myrland',
  purpose:
    'A dry cave behind the rock pile at the warm springs, where somebody kept their blasting powder: the larger bomb bag.',
  indoor: true,
  things: [
    { k: 'door', at: { x: 19, y: 15 }, dir: 's', to: 'myl_springs', arrive: { x: 35, y: 4 }, facing: 's' },
    { k: 'door', at: { x: 20, y: 15 }, dir: 's', to: 'myl_springs', arrive: { x: 36, y: 4 }, facing: 's' },
    { k: 'chest', id: 'myl_c_bombbag', at: { x: 19, y: 8 }, gives: { item: 'bomb_bag' } },
    { k: 'prop', id: 'bomb_pot', at: { x: 15, y: 9 } },
    { k: 'prop', id: 'bomb_pot', at: { x: 24, y: 9 } },
  ],
  map: [
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXQQQQQQQQQQQQQQQQXXXXXXXXXXXX',
    'XXXXXXXXXXXXQccccccccccccccQXXXXXXXXXXXX',
    'XXXXXXXXXXXXQccccccccccccccQXXXXXXXXXXXX',
    'XXXXXXXXXXXXQccccccccccccccQXXXXXXXXXXXX',
    'XXXXXXXXXXXXQccccccccccccccQXXXXXXXXXXXX',
    'XXXXXXXXXXXXQccccccccccccccQXXXXXXXXXXXX',
    'XXXXXXXXXXXXQccccccccccccccQXXXXXXXXXXXX',
    'XXXXXXXXXXXXQccccccccccccccQXXXXXXXXXXXX',
    'XXXXXXXXXXXXQccccccccccccccQXXXXXXXXXXXX',
    'XXXXXXXXXXXXQQQQQQQVVQQQQQQQXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  ],
};
