import type { FishDef } from '@core/story/fishing';
import type { FishId } from './ids';

/**
 * What bites in Mýrland, by season and part of the day, and how each fights. A fish can be landed while
 * `run × pull < 300` (the reel against the slack, see FISHING); the closer to it, the harder the fight.
 */
export const FISH_DEFS = {
  perch: {
    id: 'perch',
    name: { en: 'Perch', sv: 'Abborre' },
    silver: 3,
    seasons: ['summer', 'autumn', 'winter', 'spring'],
    weight: 6,
    dist: 400,
    pull: 6,
    run: 4,
    surge: 6,
  },
  pike: {
    id: 'pike',
    name: { en: 'Pike', sv: 'Gädda' },
    silver: 8,
    seasons: ['spring', 'autumn'],
    weight: 3,
    dist: 700,
    pull: 12,
    run: 8,
    surge: 18,
  },
  bream: {
    id: 'bream',
    name: { en: 'Bream', sv: 'Braxen' },
    silver: 5,
    seasons: ['summer'],
    weight: 4,
    dist: 500,
    pull: 8,
    run: 5,
    surge: 8,
  },
  trout: {
    id: 'trout',
    name: { en: 'Trout', sv: 'Öring' },
    silver: 10,
    seasons: ['spring', 'summer'],
    phases: ['morning', 'evening'],
    weight: 3,
    dist: 600,
    pull: 10,
    run: 8,
    surge: 14,
  },
  eel: {
    id: 'eel',
    name: { en: 'Eel', sv: 'Ål' },
    silver: 12,
    seasons: ['summer', 'autumn'],
    phases: ['night'],
    weight: 3,
    dist: 650,
    pull: 11,
    run: 9,
    surge: 16,
  },
  burbot: {
    id: 'burbot',
    name: { en: 'Burbot', sv: 'Lake' },
    silver: 8,
    seasons: ['winter'],
    phases: ['evening', 'night'],
    weight: 4,
    dist: 550,
    pull: 9,
    run: 6,
    surge: 10,
    /** Eyvindr's burbot (`q_burbot`); his ask clears it, so only one landed after counts. */
    onLand: [{ k: 'set', flag: 'q_burbot_caught', value: true }],
  },
  salmon: {
    id: 'salmon',
    name: { en: 'Salmon', sv: 'Lax' },
    silver: 15,
    seasons: ['autumn'],
    weight: 2,
    dist: 900,
    pull: 13,
    run: 10,
    surge: 20,
  },
  /** Gamli, the old pike of the millpond: only in autumn, at dawn and dusk, and he fights. */
  gamli: {
    id: 'gamli',
    name: { en: 'Gamli, the old pike', sv: 'Gamle, den gamla gäddan' },
    silver: 50,
    seasons: ['autumn'],
    phases: ['morning', 'evening'],
    weight: 1,
    dist: 1600,
    pull: 14,
    run: 9,
    surge: 30,
    onLand: [{ k: 'set', flag: 'q_fish_gamli', value: true }],
  },
} as const satisfies Record<FishId, FishDef>;
