import type { Tuning } from '@core/actors/tuning';

export const TUNING: Tuning = {
  hero: {
    walkSpeed: 1.5,
    shieldSpeed: 0.75,
    chargeSpeed: 0.75,
    rollSpeed: 3,
    rollTicks: 18,
    rollIframes: 12,
    rollCooldown: 20,
    attackTicks: 14,
    finisherTicks: 20,
    comboWindow: 8,
    swordActiveFrom: 2,
    swordActiveTo: 8,
    chargeTicks: 40,
    spinTicks: 24,
    hurtTicks: 12,
    hurtIframes: 60,
    dyingTicks: 60,
    ledgePushTicks: 6,
    hopTicks: 20,
    hopHeight: 10,
    liftTicks: 12,
    carrySpeed: 1.2,
    throwTicks: 10,
    tossTicks: 10,
    carryHeight: 18,
    body: { x: -6, y: -8, w: 12, h: 8 },
    hurt: { x: -7, y: -26, w: 14, h: 26 },
  },
  sword: {
    comboDamage: [2, 2, 4],
    spinDamage: 4,
    knock: 4,
    boxes: {
      e: { x: 2, y: -24, w: 20, h: 20 },
      w: { x: -22, y: -24, w: 20, h: 20 },
      n: { x: -10, y: -40, w: 20, h: 22 },
      s: { x: -10, y: -8, w: 20, h: 20 },
    },
    spinBox: { x: -26, y: -36, w: 52, h: 44 },
  },
  throw: { speed: 4, flightTicks: 20 },
  push: { ticks: 16, slideTicks: 16 },
  boomerang: { speed: 3, range: 112 },
  weapons: {
    /** The pitchfork of the raid night: long reach, light blows. */
    pitchfork: {
      comboDamage: [1, 1, 2],
      spinDamage: 2,
      knock: 5,
      boxes: {
        e: { x: 2, y: -20, w: 26, h: 14 },
        w: { x: -28, y: -20, w: 26, h: 14 },
        n: { x: -6, y: -44, w: 12, h: 26 },
        s: { x: -6, y: -8, w: 12, h: 24 },
      },
      spinBox: { x: -26, y: -36, w: 52, h: 44 },
    },
    /** The Uppvík smith's sword: a little longer than the seax, and it bites half again as deep. */
    uppvik_sword: {
      comboDamage: [3, 3, 6],
      spinDamage: 6,
      knock: 4,
      boxes: {
        e: { x: 2, y: -24, w: 22, h: 20 },
        w: { x: -24, y: -24, w: 22, h: 20 },
        n: { x: -10, y: -42, w: 20, h: 24 },
        s: { x: -10, y: -8, w: 20, h: 22 },
      },
      spinBox: { x: -28, y: -38, w: 56, h: 48 },
    },
    /** The farm hand-axe: short reach, light blows. */
    handaxe: {
      comboDamage: [1, 1, 2],
      spinDamage: 2,
      knock: 3,
      boxes: {
        e: { x: 2, y: -22, w: 16, h: 18 },
        w: { x: -18, y: -22, w: 16, h: 18 },
        n: { x: -8, y: -36, w: 16, h: 18 },
        s: { x: -8, y: -8, w: 16, h: 16 },
      },
      spinBox: { x: -22, y: -32, w: 44, h: 40 },
    },
  },
  armor: {
    wool_tunic: { reduce: 0 },
    byrnie: { reduce: 0.25 },
    ember_byrnie: { reduce: 0.4 },
    runeplate: { reduce: 0.5 },
  },
  textCps: 45,
  enemyIframes: 6,
  knockDecay: 0.8,
};
