import type { DevPreset } from '@core/dev/query';

const DAY1_DONE = {
  st_intro_seen: true,
  q_sheep_d1: true,
  q_water_d1: true,
  q_paid_d1: true,
  ev_embla_d1: true,
} as const;
const DAY2_DONE = { ...DAY1_DONE, q_logs: 5, q_paid_d2: true, ev_embla_d2: true } as const;
const DAY3_DONE = { ...DAY2_DONE, st_farm_day: 3, q_ravens: 5, q_paid_d3: true, ev_embla_d3: true } as const;
/** The prologue as the M1a route leaves it: silver spent on the lantern, which hangs in slot K. */
const LANTERN = { items: { lantern: 1 }, slots: ['lantern', null] } as const;

/** Where the M1b route leaves Ask: the raid over, the legend told, the gate north open. */
const MYR_FLAGS = {
  ...DAY3_DONE,
  st_raid_begun: true,
  st_raid_done: true,
  st_seax_given: true,
  st_legend_told: true,
} as const;

/** Dev starting points for `?preset=`. Content milestones add story presets (day2, night3, …). */
/** Everything M2 sets on the way: the road north, Uppvík, Eldr, and the vargar hunt paid. */
const AFTER_M2 = {
  ...MYR_FLAGS,
  n_onundr_met: true,
  n_dagny_met: true,
  n_skeggi_met: true,
  n_thordis_met: true,
  n_hrafnkell_met: true,
  n_solvi_met: true,
  n_bersi_met: true,
  st_d1_entered: true,
  st_d1_boss_dead: true,
  st_stone1_lit: true,
  st_road_open: true,
  st_uppvik_reached: true,
  w_horn_thordis: true,
  q_eldr_asked: true,
  st_eldr_learned: true,
  q_vargar_taken: true,
  q_vargar_tracked: true,
  q_vargar_alpha: true,
  q_vargar_done: true,
} as const;

/** And what M3a sets: over the weir into Mýrland, and Þuríðr's tale of the drowned mill heard. */
const MYL_FLAGS = {
  ...AFTER_M2,
  w_myl_bridge: true,
  st_myrland_reached: true,
  n_thuridr_met: true,
  q_rs2_mill: true,
} as const;

/**
 * The end of M5a: the pass open in the Fimbulvetr winter, Styrr's duel won and Bragð learned, with silver
 * enough for Sölvi's Hlíf. Askdalr's homecoming is still to come.
 */
const FIMBUL = {
  screen: 'hau_pass',
  tile: [20, 8],
  facing: 's',
  weapon: 'seax',
  shield: true,
  minute: 10 * 60,
  season: 'winter',
  policy: 'cycling',
  silver: 150,
  items: { lantern: 1, boomerang: 1, horn: 2, mead_red: 2, purse: 1, bombs: 10, bow: 1, arrows: 30 },
  slots: ['bow', 'bombs'],
  galdr: ['eldr', 'farvegr', 'bragd'],
  seidr: 10,
  flags: {
    ...MYL_FLAGS,
    st_d2_entered: true,
    st_d2_boss_dead: true,
    st_stone2_lit: true,
    st_haugar_reached: true,
    n_styrr_met: true,
    q_rs3_watch: true,
    q_watch_kills: 3,
    st_barrow_open: true,
    t_dash: true,
    t_parry: true,
    st_d3_entered: true,
    st_d3_warden: true,
    st_d3_boss_dead: true,
    st_stone3_lit: true,
    q_duel_asked: true,
    q_duel_won: true,
    st_bragd_learned: true,
    st_pass_open: true,
  },
  vars: { ask_pen: 31 },
  maxHp: 28,
  hp: 28,
  pieces: ['hp_d1_r09', 'hp_myl_peat', 'hp_hau_barrows', 'hp_hau_tarn'],
  opened: ['d1_hc', 'd2_hc', 'd3_hc', 'd2_c_bombs', 'd3_c_bow', 'hau_k_gully', 'hau_k_barrows'],
  dungeons: { d1: { bossDead: true }, d2: { bossDead: true }, d3: { bossDead: true } },
  warps: ['haugar'],
} as const satisfies DevPreset;

/** And what M5b and M6a set on the way to Helgrind's gate. */
const AFTER_RIME = {
  ...FIMBUL.flags,
  st_home_winter: true,
  st_blood_told: true,
  st_hlif_learned: true,
  st_rime_open: true,
  st_niflmyrr_reached: true,
  st_twist_heard: true,
  q_ljos_asked: true,
  q_ljos_done: true,
} as const;

/** Everything up to Útgarðr's gate (M10): all four thanes down, every captive home, Embla found. */
const THANES_DOWN = {
  st_thane_nastrond: true,
  st_thane_nykr: true,
  st_thane_ivaldi: true,
  st_thane_hrimgerdr: true,
  q_thanes: 4,
  q_captives: 8,
  st_dvg_reached: true,
  q_foreman: 5,
  st_embla_found: true,
  q_letters: 3,
  q_trade: 7,
  st_hrf_reached: true,
  st_beacon_lit: true,
  w_ring_beacon: true,
} as const;

export const DEV_PRESETS = {
  /** The M0 test kit: seax and shield in the test lands. */
  m0: { screen: 'test_a', tile: [10, 11], weapon: 'seax', shield: true },
  /** Morning of the second farm day, in the farmyard. */
  day2: {
    screen: 'ask_farmyard',
    tile: [14, 12],
    weapon: 'handaxe',
    shield: false,
    minute: 6 * 60,
    silver: 10,
    flags: { ...DAY1_DONE, st_farm_day: 2 },
    vars: { ask_pen: 31 },
  },
  /** Morning of the third farm day, in the farmyard. */
  day3: {
    screen: 'ask_farmyard',
    tile: [14, 12],
    weapon: 'handaxe',
    shield: false,
    minute: 6 * 60,
    silver: 20,
    flags: { ...DAY2_DONE, st_farm_day: 3 },
    vars: { ask_pen: 31 },
  },
  /** The third evening, by Ask's bed: sleeping now starts the raid. */
  night3: {
    screen: 'ask_int_longhouse',
    tile: [10, 8],
    facing: 'n',
    weapon: 'handaxe',
    shield: false,
    minute: 21 * 60,
    silver: 30,
    flags: DAY3_DONE,
    vars: { ask_pen: 31 },
  },
  /** The raid night: Ask has just woken to fire, pitchfork in hand. */
  raid: {
    screen: 'ask_int_longhouse',
    tile: [10, 8],
    facing: 's',
    weapon: 'pitchfork',
    shield: false,
    minute: 2 * 60,
    season: 'autumn',
    silver: 5,
    ...LANTERN,
    flags: { ...DAY3_DONE, st_raid_begun: true },
    vars: { ask_pen: 31 },
  },
  /** The morning after the raid, by Halvar's bed. */
  morning: {
    screen: 'ask_int_longhouse',
    tile: [25, 8],
    facing: 'e',
    weapon: 'pitchfork',
    shield: false,
    minute: 7 * 60,
    season: 'autumn',
    silver: 5,
    ...LANTERN,
    flags: { ...DAY3_DONE, st_raid_begun: true, st_raid_done: true },
    vars: { ask_pen: 31 },
  },
  /** Myrkviðr after the legend: seax and shield, the lantern, the clock turning. */
  myr: {
    screen: 'myr_road_s',
    tile: [19, 18],
    facing: 'n',
    weapon: 'seax',
    shield: true,
    minute: 9 * 60,
    season: 'autumn',
    policy: 'cycling',
    silver: 5,
    ...LANTERN,
    flags: MYR_FLAGS,
    vars: { ask_pen: 31 },
  },
  /** Myrkviðr in autumn with Eldr learned and a full seiðr bar: burn the leaf piles. */
  eldr: {
    screen: 'myr_pines',
    tile: [20, 10],
    facing: 'w',
    weapon: 'seax',
    shield: true,
    minute: 12 * 60,
    season: 'autumn',
    policy: 'cycling',
    silver: 40,
    ...LANTERN,
    flags: MYR_FLAGS,
    vars: { ask_pen: 31 },
    galdr: ['eldr'],
  },
  /** After Rótarhellir, by Önundr in his clearing: he saws the pine, and the road north opens. */
  north: {
    screen: 'myr_clearing',
    tile: [23, 12],
    facing: 'n',
    weapon: 'seax',
    shield: true,
    minute: 10 * 60,
    season: 'autumn',
    policy: 'cycling',
    silver: 30,
    items: { lantern: 1, boomerang: 1 },
    slots: ['lantern', 'boomerang'],
    flags: {
      ...MYR_FLAGS,
      n_onundr_met: true,
      st_d1_entered: true,
      st_d1_boss_dead: true,
      st_stone1_lit: true,
    },
    vars: { ask_pen: 31 },
    maxHp: 16,
    hp: 16,
    pieces: ['hp_d1_r09'],
    opened: ['d1_hc'],
    dungeons: { d1: { bossDead: true } },
  },
  /** A winter night on the Myrkviðr road, half an hour before sunrise: snow, rolled foes and trolls. */
  turning: {
    screen: 'myr_road',
    tile: [20, 18],
    facing: 'n',
    weapon: 'seax',
    shield: true,
    minute: 6 * 60 + 30,
    season: 'winter',
    policy: 'cycling',
    silver: 5,
    ...LANTERN,
    flags: MYR_FLAGS,
    vars: { ask_pen: 31 },
  },

  /** Uppvík's square at noon, newly arrived: the road open, silver for the smith, no horn yet. */
  uppvik: {
    screen: 'upp_square',
    tile: [20, 14],
    facing: 'n',
    weapon: 'seax',
    shield: true,
    minute: 12 * 60,
    season: 'autumn',
    policy: 'cycling',
    silver: 100,
    items: { lantern: 1, boomerang: 1 },
    slots: ['lantern', 'boomerang'],
    flags: {
      ...MYR_FLAGS,
      n_onundr_met: true,
      st_d1_entered: true,
      st_d1_boss_dead: true,
      st_stone1_lit: true,
      st_road_open: true,
      st_uppvik_reached: true,
    },
    vars: { ask_pen: 31 },
    maxHp: 16,
    hp: 16,
    pieces: ['hp_d1_r09'],
    opened: ['d1_hc'],
    dungeons: { d1: { bossDead: true } },
  },

  /** Where M2b leaves Ask: back in Uppvík's square with Eldr, a horn of red mead and little silver. */
  hunt: {
    screen: 'upp_square',
    tile: [22, 14],
    facing: 'n',
    weapon: 'seax',
    shield: true,
    minute: 13 * 60,
    season: 'autumn',
    policy: 'cycling',
    silver: 10,
    items: { lantern: 1, boomerang: 1, horn: 1, mead_red: 1 },
    slots: ['lantern', 'boomerang'],
    galdr: ['eldr'],
    flags: {
      ...MYR_FLAGS,
      n_onundr_met: true,
      n_dagny_met: true,
      n_skeggi_met: true,
      n_thordis_met: true,
      n_hrafnkell_met: true,
      n_solvi_met: true,
      st_d1_entered: true,
      st_d1_boss_dead: true,
      st_stone1_lit: true,
      st_road_open: true,
      st_uppvik_reached: true,
      w_horn_thordis: true,
      q_eldr_asked: true,
      st_eldr_learned: true,
    },
    vars: { ask_pen: 31 },
    maxHp: 16,
    hp: 16,
    pieces: ['hp_d1_r09'],
    opened: ['d1_hc'],
    dungeons: { d1: { bossDead: true } },
  },

  /**
   * Where M2 leaves Ask, come down the forest brook to the bank path into Mýrland: the boomerang in slot K,
   * Eldr, the hunt paid. The weir's latch is still up.
   */
  myl: {
    screen: 'myr_brook',
    tile: [35, 17],
    facing: 's',
    weapon: 'seax',
    shield: true,
    minute: 10 * 60,
    season: 'autumn',
    policy: 'cycling',
    silver: 70,
    items: { lantern: 1, boomerang: 1, horn: 1, mead_red: 1, purse: 1 },
    slots: ['boomerang', 'lantern'],
    galdr: ['eldr'],
    flags: AFTER_M2,
    vars: { ask_pen: 31 },
    maxHp: 16,
    hp: 16,
    pieces: ['hp_d1_r09'],
    opened: ['d1_hc'],
    dungeons: { d1: { bossDead: true } },
  },
  /** At the end of Kári's jetty with his rod lent, on an autumn evening: Gamli may bite. */
  fisher: {
    screen: 'myl_fisher',
    tile: [20, 3],
    facing: 'n',
    weapon: 'seax',
    shield: true,
    minute: 18 * 60 + 30,
    season: 'autumn',
    policy: 'cycling',
    silver: 70,
    items: { lantern: 1, boomerang: 1, horn: 1, mead_red: 1, purse: 1 },
    slots: ['boomerang', 'lantern'],
    galdr: ['eldr'],
    flags: { ...AFTER_M2, w_myl_bridge: true, st_myrland_reached: true, n_kari_met: true },
    vars: { ask_pen: 31 },
    maxHp: 16,
    hp: 16,
    pieces: ['hp_d1_r09'],
    opened: ['d1_hc'],
    dungeons: { d1: { bossDead: true } },
  },

  /** By the millpond after Sökkva Kvern, with bombs in slot K: for the springs' cave and the peat's crack. */
  mylbombs: {
    screen: 'myl_mill',
    tile: [18, 16],
    facing: 's',
    weapon: 'seax',
    shield: true,
    minute: 10 * 60,
    season: 'autumn',
    policy: 'cycling',
    silver: 70,
    items: { lantern: 1, boomerang: 1, horn: 1, mead_red: 1, purse: 1, bombs: 10 },
    slots: ['bombs', 'boomerang'],
    galdr: ['eldr'],
    flags: { ...MYL_FLAGS, st_d2_entered: true, st_d2_boss_dead: true, st_stone2_lit: true },
    vars: { ask_pen: 31 },
    maxHp: 20,
    hp: 20,
    pieces: ['hp_d1_r09'],
    opened: ['d1_hc', 'd2_hc', 'd2_c_bombs'],
    dungeons: { d1: { bossDead: true }, d2: { bossDead: true } },
  },
  /**
   * Where M3 leaves Ask: the second stone lit, in the birch glade by the path east to Haugar's rockfall,
   * with bombs, the boomerang, two horns of red mead, five hearts and silver enough for Styrr's lessons.
   */
  hau: {
    screen: 'myr_glade',
    tile: [34, 17],
    facing: 'e',
    weapon: 'seax',
    shield: true,
    minute: 10 * 60,
    season: 'autumn',
    policy: 'cycling',
    silver: 150,
    items: { lantern: 1, boomerang: 1, horn: 2, mead_red: 2, purse: 1, bombs: 10 },
    slots: ['bombs', 'boomerang'],
    galdr: ['eldr'],
    flags: { ...MYL_FLAGS, st_d2_entered: true, st_d2_boss_dead: true, st_stone2_lit: true },
    vars: { ask_pen: 31 },
    maxHp: 20,
    hp: 20,
    pieces: ['hp_d1_r09'],
    opened: ['d1_hc', 'd2_hc', 'd2_c_bombs'],
    dungeons: { d1: { bossDead: true }, d2: { bossDead: true } },
  },
  /**
   * The barrow-watch about to begin: before the King's Barrow at 23:00, Styrr's word given and both his
   * lessons learned.
   */
  watch: {
    screen: 'hau_king',
    tile: [20, 19],
    facing: 'n',
    weapon: 'seax',
    shield: true,
    minute: 23 * 60,
    season: 'autumn',
    policy: 'cycling',
    silver: 20,
    items: { lantern: 1, boomerang: 1, horn: 2, mead_red: 2, purse: 1, bombs: 9 },
    slots: ['bombs', 'boomerang'],
    galdr: ['eldr'],
    flags: {
      ...MYL_FLAGS,
      st_d2_entered: true,
      st_d2_boss_dead: true,
      st_stone2_lit: true,
      st_haugar_reached: true,
      n_styrr_met: true,
      q_rs3_watch: true,
      t_dash: true,
      t_parry: true,
    },
    vars: { ask_pen: 31 },
    maxHp: 20,
    hp: 20,
    pieces: ['hp_d1_r09'],
    opened: ['d1_hc', 'd2_hc', 'd2_c_bombs', 'hau_k_gully'],
    dungeons: { d1: { bossDead: true }, d2: { bossDead: true } },
  },
  /**
   * Just inside Konungshaugr's door after the barrow-watch: both of Styrr's lessons, bombs and the
   * boomerang, two horns of red mead and six hearts (the two dungeon hearts and four pieces).
   */
  d3: {
    screen: 'd3_r01',
    tile: [19, 18],
    facing: 'n',
    weapon: 'seax',
    shield: true,
    minute: 23 * 60,
    season: 'autumn',
    policy: 'cycling',
    silver: 40,
    items: { lantern: 1, boomerang: 1, horn: 2, mead_red: 2, purse: 1, bombs: 10 },
    slots: ['boomerang', 'bombs'],
    galdr: ['eldr'],
    flags: {
      ...MYL_FLAGS,
      st_d2_entered: true,
      st_d2_boss_dead: true,
      st_stone2_lit: true,
      st_haugar_reached: true,
      n_styrr_met: true,
      q_rs3_watch: true,
      q_watch_kills: 3,
      st_barrow_open: true,
      t_dash: true,
      t_parry: true,
    },
    vars: { ask_pen: 31 },
    maxHp: 24,
    hp: 24,
    pieces: ['hp_d1_r09', 'hp_myl_peat', 'hp_hau_barrows', 'hp_hau_tarn'],
    opened: ['d1_hc', 'd2_hc', 'd2_c_bombs', 'hau_k_gully', 'hau_k_barrows'],
    dungeons: { d1: { bossDead: true }, d2: { bossDead: true } },
    warps: ['haugar'],
  },
  /** Before the King's great door in the champions' hall, with the bow, the great key and a full quiver. */
  d3boss: {
    screen: 'd3_r13',
    tile: [19, 3],
    facing: 'n',
    weapon: 'seax',
    shield: true,
    minute: 23 * 60,
    season: 'autumn',
    policy: 'cycling',
    silver: 40,
    items: { lantern: 1, boomerang: 1, horn: 2, mead_red: 2, purse: 1, bombs: 10, bow: 1, arrows: 30 },
    slots: ['bow', 'bombs'],
    galdr: ['eldr'],
    flags: {
      ...MYL_FLAGS,
      st_d2_entered: true,
      st_d2_boss_dead: true,
      st_stone2_lit: true,
      st_haugar_reached: true,
      n_styrr_met: true,
      q_rs3_watch: true,
      q_watch_kills: 3,
      st_barrow_open: true,
      t_dash: true,
      t_parry: true,
      st_d3_entered: true,
      st_d3_warden: true,
      w_d3_r10: true,
      w_d3_r12: true,
    },
    vars: { ask_pen: 31 },
    maxHp: 24,
    hp: 24,
    pieces: ['hp_d1_r09', 'hp_myl_peat', 'hp_hau_barrows', 'hp_hau_tarn'],
    opened: [
      'd1_hc',
      'd2_hc',
      'd2_c_bombs',
      'hau_k_gully',
      'hau_k_barrows',
      'd3_c_key1',
      'd3_c_key2',
      'd3_c_key3',
      'd3_c_map',
      'd3_c_bow',
      'd3_c_bigkey',
    ],
    dungeons: {
      d1: { bossDead: true },
      d2: { bossDead: true },
      d3: {
        keys: 0,
        bigKey: true,
        map: true,
        doors: ['d3_lock_a', 'd3_lock_b', 'd3_lock_c', 'd3_sh_r02', 'd3_sh_r09w', 'd3_sh_r09e'],
      },
    },
  },
  /** Where M4 leaves Ask: the third stone lit, Farvegr known, back at the barrow's door with the bow. */
  haubow: {
    screen: 'hau_king',
    tile: [20, 12],
    facing: 's',
    weapon: 'seax',
    shield: true,
    minute: 10 * 60,
    season: 'autumn',
    policy: 'cycling',
    silver: 90,
    items: { lantern: 1, boomerang: 1, horn: 2, mead_red: 2, purse: 1, bombs: 10, bow: 1, arrows: 30 },
    slots: ['bow', 'bombs'],
    galdr: ['eldr', 'farvegr'],
    seidr: 10,
    flags: {
      ...MYL_FLAGS,
      st_d2_entered: true,
      st_d2_boss_dead: true,
      st_stone2_lit: true,
      st_haugar_reached: true,
      n_styrr_met: true,
      q_rs3_watch: true,
      q_watch_kills: 3,
      st_barrow_open: true,
      t_dash: true,
      t_parry: true,
      st_d3_entered: true,
      st_d3_warden: true,
      st_d3_boss_dead: true,
      st_stone3_lit: true,
    },
    vars: { ask_pen: 31 },
    maxHp: 28,
    hp: 28,
    pieces: ['hp_d1_r09', 'hp_myl_peat', 'hp_hau_barrows', 'hp_hau_tarn'],
    opened: ['d1_hc', 'd2_hc', 'd3_hc', 'd2_c_bombs', 'd3_c_bow', 'hau_k_gully', 'hau_k_barrows'],
    dungeons: { d1: { bossDead: true }, d2: { bossDead: true }, d3: { bossDead: true } },
    warps: ['haugar'],
  },
  /**
   * The end of M5a: the pass open in the Fimbulvetr winter, Styrr's duel won and Bragð learned, with silver
   * enough for Sölvi's Hlíf. Askdalr's homecoming is still to come.
   */
  fimbul: FIMBUL,
  /** Home in the Fimbulvetr by Halvar's bed, with silver enough for both farm stages (150 and 250) in the big purse. */
  farm: {
    ...FIMBUL,
    screen: 'ask_int_longhouse',
    tile: [27, 9],
    facing: 'n',
    silver: 400,
    items: { ...FIMBUL.items, purse: 2 },
    flags: { ...FIMBUL.flags, st_home_winter: true, st_blood_told: true },
  },
  /**
   * Before Helgrind's gate, as M6a leaves Ask: the rime melted, Niflmýrr reached and the twist heard, Hlíf
   * and Ljós known, two Ís staves (one readied in slot K) and eight hearts.
   */
  d4: {
    ...FIMBUL,
    screen: 'nif_gate',
    tile: [20, 7],
    facing: 'n',
    minute: 23 * 60,
    silver: 70,
    items: { ...FIMBUL.items, stave_is: 2 },
    slots: ['stave_is', 'bombs'],
    galdr: ['eldr', 'farvegr', 'bragd', 'hlif', 'ljos'],
    flags: { ...AFTER_RIME },
    maxHp: 32,
    hp: 32,
  },
  /**
   * Before Náströnd's great door in Helgrind's hub, with everything D4 gives: the grapple in slot K, Ís
   * learned, the great key, Garmr dead and every lock open.
   */
  d4boss: {
    ...FIMBUL,
    screen: 'd4_r13',
    tile: [19, 3],
    facing: 'n',
    minute: 23 * 60,
    silver: 70,
    items: { ...FIMBUL.items, stave_is: 2, grapple: 1 },
    slots: ['grapple', 'bombs'],
    galdr: ['eldr', 'farvegr', 'bragd', 'hlif', 'ljos', 'is'],
    flags: { ...AFTER_RIME, st_d4_entered: true, st_d4_garmr: true },
    maxHp: 32,
    hp: 32,
    opened: [
      ...FIMBUL.opened,
      'd4_c_key1',
      'd4_c_key2',
      'd4_c_key3',
      'd4_c_map',
      'd4_c_compass',
      'd4_c_grapple',
      'd4_c_is',
      'd4_c_bigkey',
    ],
    dungeons: {
      ...FIMBUL.dungeons,
      d4: {
        keys: 0,
        bigKey: true,
        map: true,
        compass: true,
        doors: ['d4_lock_a', 'd4_lock_b', 'd4_lock_c', 'd4_sh_r07n', 'd4_sh_r07e'],
      },
    },
  },
  /**
   * On Holmr's ford in Sævatn, as M6b leaves Ask and Hrafn's nights won: the seal-skin, the grapple in slot
   * K, Ís learned, Náströnd dead and the captives freed, nine hearts. Embla is not yet found.
   */
  sae: {
    ...FIMBUL,
    screen: 'sae_holmr_ford',
    tile: [21, 3],
    facing: 'n',
    minute: 12 * 60,
    silver: 70,
    items: { ...FIMBUL.items, stave_is: 2, grapple: 1, sealskin: 1, trade_comb: 1 },
    slots: ['grapple', 'bombs'],
    galdr: ['eldr', 'farvegr', 'bragd', 'hlif', 'ljos', 'is'],
    flags: {
      ...AFTER_RIME,
      st_d4_entered: true,
      st_d4_garmr: true,
      st_d4_boss_dead: true,
      st_thane_nastrond: true,
      st_freed_ulf: true,
      st_freed_tofa: true,
      q_thanes: 1,
      q_captives: 2,
      q_trade: 4,
      n_hrafn_met: true,
      q_sealskin_asked: true,
      q_seal_nights: 3,
      q_sealskin_done: true,
    },
    maxHp: 36,
    hp: 36,
  },
  /**
   * In Sökkva Hof's hub before the great door, as the M7b route stands there: Embla found, Hrönn dead, Vindr
   * learned, the second key unspent and the great key carried, the water at the top level, ten hearts.
   */
  hof: {
    ...FIMBUL,
    screen: 'd5_r13',
    tile: [19, 3],
    facing: 'n',
    minute: 23 * 60,
    silver: 20,
    items: { ...FIMBUL.items, stave_is: 3, grapple: 1, sealskin: 1, mead_green: 1, ore: 8 },
    slots: ['grapple', 'bombs'],
    galdr: ['vindr', 'eldr', 'farvegr', 'bragd', 'hlif', 'ljos', 'is'],
    flags: {
      ...AFTER_RIME,
      st_d4_entered: true,
      st_d4_garmr: true,
      st_d4_boss_dead: true,
      st_thane_nastrond: true,
      st_freed_ulf: true,
      st_freed_tofa: true,
      q_thanes: 1,
      q_captives: 2,
      q_trade: 5,
      n_hrafn_met: true,
      q_sealskin_asked: true,
      q_seal_nights: 3,
      q_sealskin_done: true,
      st_embla_found: true,
      q_letters: 1,
      st_d5_entered: true,
      st_d5_hronn: true,
      w_d5_r14: true,
      w_d5_level: 2,
    },
    maxHp: 40,
    hp: 40,
    opened: [
      ...FIMBUL.opened,
      'd5_c_key1',
      'd5_c_key2',
      'd5_c_key3',
      'd5_c_map',
      'd5_c_compass',
      'd5_c_vindr',
      'd5_c_r05',
      'd5_c_bigkey',
    ],
    dungeons: {
      ...FIMBUL.dungeons,
      d5: {
        keys: 1,
        bigKey: true,
        map: true,
        compass: true,
        doors: ['d5_lock_a', 'd5_lock_b', 'd5_sh_r11n'],
      },
    },
  },
  /**
   * Dvergagröf's camp after M7b (M8a): over the chasm, Nykr dead and the loom woven, the sail-needle and
   * fourteen ore in the pack, Dvalinn not yet met.
   */
  dvg: {
    ...FIMBUL,
    screen: 'dvg_camp',
    tile: [22, 10],
    facing: 'n',
    minute: 10 * 60,
    silver: 20,
    items: { ...FIMBUL.items, stave_is: 3, grapple: 1, sealskin: 1, mead_green: 1, ore: 14, trade_needle: 1 },
    slots: ['grapple', 'bombs'],
    galdr: ['vindr', 'eldr', 'farvegr', 'bragd', 'hlif', 'ljos', 'is'],
    flags: {
      ...AFTER_RIME,
      st_d4_entered: true,
      st_d4_garmr: true,
      st_d4_boss_dead: true,
      st_thane_nastrond: true,
      st_freed_ulf: true,
      st_freed_tofa: true,
      q_trade: 5,
      n_hrafn_met: true,
      q_sealskin_asked: true,
      q_seal_nights: 3,
      q_sealskin_done: true,
      st_embla_found: true,
      q_letters: 1,
      st_d5_entered: true,
      st_d5_boss_dead: true,
      st_thane_nykr: true,
      st_freed_oddr: true,
      st_freed_hallbera: true,
      q_thanes: 2,
      q_captives: 4,
      st_loom_woven: true,
      st_dvg_reached: true,
    },
    maxHp: 40,
    hp: 40,
  },
  /** Inside Ívaldi's Forge's gate hall (M8b), with what M8a gives: the byrnie, and ore for Sindri. */
  d6: {
    ...FIMBUL,
    screen: 'd6_r25',
    tile: [19, 17],
    facing: 'n',
    minute: 10 * 60,
    silver: 20,
    armor: 'ember_byrnie',
    items: { ...FIMBUL.items, stave_is: 3, grapple: 1, sealskin: 1, mead_green: 1, ore: 2 },
    slots: ['grapple', 'bombs'],
    galdr: ['vindr', 'eldr', 'farvegr', 'bragd', 'hlif', 'ljos', 'is'],
    flags: {
      ...AFTER_RIME,
      st_d4_entered: true,
      st_d4_garmr: true,
      st_d4_boss_dead: true,
      st_thane_nastrond: true,
      st_freed_ulf: true,
      st_freed_tofa: true,
      st_embla_found: true,
      st_d5_entered: true,
      st_d5_boss_dead: true,
      st_thane_nykr: true,
      st_freed_oddr: true,
      st_freed_hallbera: true,
      q_thanes: 2,
      q_captives: 4,
      st_loom_woven: true,
      st_dvg_reached: true,
      q_foreman: 5,
      st_d6_entered: true,
    },
    maxHp: 40,
    hp: 40,
  },
  /** Before Ívaldi's great door (M8b): the hammer in slot K, the Skjálfti stave in L, the great key. */
  d6boss: {
    ...FIMBUL,
    screen: 'd6_r11',
    tile: [19, 3],
    facing: 'n',
    minute: 10 * 60,
    silver: 20,
    armor: 'ember_byrnie',
    items: { ...FIMBUL.items, stave_is: 1, stave_skjalfti: 1, grapple: 1, sealskin: 1, hammer: 1, ore: 9 },
    slots: ['hammer', 'stave_skjalfti'],
    galdr: ['vindr', 'eldr', 'farvegr', 'bragd', 'hlif', 'ljos', 'is', 'skjalfti'],
    flags: {
      ...AFTER_RIME,
      st_thane_nastrond: true,
      st_thane_nykr: true,
      q_thanes: 2,
      q_captives: 4,
      st_dvg_reached: true,
      q_foreman: 5,
      st_d6_entered: true,
      st_d6_belgr: true,
      w_d6_belts: true,
    },
    maxHp: 44,
    hp: 44,
    dungeons: { d6: { bigKey: true, map: true, compass: true } },
  },
  /**
   * Hrímfjöll's beacon hill by its warp stone (M9), in winter: the ember byrnie against the killing frost,
   * the grapple in slot K and bombs in L, Sindri's lens for Ormr, and three thanes fallen.
   */
  hrf: {
    ...FIMBUL,
    screen: 'hrf_beacon',
    tile: [20, 16],
    facing: 'n',
    minute: 10 * 60,
    silver: 20,
    armor: 'ember_byrnie',
    items: { ...FIMBUL.items, grapple: 1, sealskin: 1, hammer: 1, ore: 1, trade_lens: 1 },
    slots: ['grapple', 'bombs'],
    galdr: ['vindr', 'eldr', 'farvegr', 'bragd', 'hlif', 'ljos', 'is', 'skjalfti'],
    flags: {
      ...AFTER_RIME,
      st_thane_nastrond: true,
      st_thane_nykr: true,
      st_thane_ivaldi: true,
      q_thanes: 3,
      q_captives: 6,
      st_dvg_reached: true,
      q_foreman: 5,
      st_embla_found: true,
      q_letters: 2,
      q_trade: 6,
      st_hrf_reached: true,
    },
    maxHp: 48,
    hp: 48,
    warps: ['haugar', 'saevatn', 'dvergagrof', 'hrimfjoll'],
  },
  /**
   * Inside Hrímturn (M9b), Svellr broken and the ice mirror in slot K, standing in the mirror hall's beam
   * (30, 13): hold K and face east to light the eye.
   */
  d7: {
    ...FIMBUL,
    screen: 'd7_r23',
    tile: [30, 13],
    facing: 'e',
    minute: 10 * 60,
    silver: 20,
    armor: 'ember_byrnie',
    items: { ...FIMBUL.items, grapple: 1, sealskin: 1, hammer: 1, ore: 1, mirror: 1 },
    slots: ['mirror', 'bombs'],
    galdr: ['vindr', 'eldr', 'farvegr', 'bragd', 'hlif', 'ljos', 'is', 'skjalfti'],
    flags: {
      ...AFTER_RIME,
      st_thane_nastrond: true,
      st_thane_nykr: true,
      st_thane_ivaldi: true,
      q_thanes: 3,
      q_captives: 6,
      st_dvg_reached: true,
      q_foreman: 5,
      st_embla_found: true,
      q_letters: 3,
      q_trade: 7,
      st_hrf_reached: true,
      st_beacon_lit: true,
      w_ring_beacon: true,
      st_d7_entered: true,
      st_d7_eye_r30: true,
      st_d7_svellr: true,
    },
    maxHp: 48,
    hp: 48,
    warps: ['haugar', 'saevatn', 'dvergagrof', 'hrimfjoll'],
  },
  /** Útgarðr's seal hall with all three seals burning (M10a): the rime door east to the vault has melted. */
  d8: {
    ...FIMBUL,
    screen: 'd8_r20',
    tile: [34, 10],
    facing: 'e',
    minute: 10 * 60,
    silver: 20,
    armor: 'ember_byrnie',
    items: { ...FIMBUL.items, grapple: 1, sealskin: 1, hammer: 1, ore: 1, mirror: 1 },
    slots: ['mirror', 'bombs'],
    galdr: ['vindr', 'eldr', 'farvegr', 'bragd', 'hlif', 'ljos', 'is', 'skjalfti'],
    flags: {
      ...AFTER_RIME,
      ...THANES_DOWN,
      st_halvar_confessed: true,
      st_utgard_open: true,
      st_d8_entered: true,
      st_d8_seal_w: true,
      st_d8_seal_e: true,
      st_d8_seal_n: true,
    },
    maxHp: 52,
    hp: 52,
    warps: ['haugar', 'saevatn', 'dvergagrof', 'hrimfjoll'],
  },
  /** The binding hall (M10b): Embla holds the binding, and Hrímnir is waking. Kolbeinn was spared. */
  d8king: {
    ...FIMBUL,
    screen: 'd8_r12',
    tile: [20, 11],
    facing: 'n',
    minute: 10 * 60,
    silver: 20,
    armor: 'ember_byrnie',
    items: { ...FIMBUL.items, grapple: 1, sealskin: 1, hammer: 1, ore: 1, mirror: 1 },
    slots: ['mirror', 'bombs'],
    galdr: ['vindr', 'eldr', 'farvegr', 'bragd', 'hlif', 'ljos', 'is', 'skjalfti'],
    flags: {
      ...AFTER_RIME,
      ...THANES_DOWN,
      st_halvar_confessed: true,
      st_utgard_open: true,
      st_d8_entered: true,
      st_d8_seal_w: true,
      st_d8_seal_e: true,
      st_d8_seal_n: true,
      st_d8_warden: true,
      st_d8_kolbeinn_met: true,
      st_kolbeinn_beaten: true,
      st_kolbeinn_spared: true,
      st_d8_embla: true,
    },
    maxHp: 52,
    hp: 52,
    warps: ['haugar', 'saevatn', 'dvergagrof', 'hrimfjoll'],
  },
  /**
   * Just inside Sökkva Kvern's door, Þuríðr's tale heard: the boomerang in slot K, the water low, two horns
   * of red mead (Hrafnkell sells the second horn), and five hearts (Rótarhellir's heart and four of the
   * seven pieces to be had before here).
   */
  d2: {
    screen: 'd2_r01',
    tile: [19, 18],
    facing: 'n',
    weapon: 'seax',
    shield: true,
    minute: 10 * 60,
    season: 'autumn',
    policy: 'cycling',
    silver: 70,
    items: { lantern: 1, boomerang: 1, horn: 2, mead_red: 2, purse: 1 },
    slots: ['boomerang', 'lantern'],
    galdr: ['eldr'],
    flags: { ...MYL_FLAGS, st_d2_entered: true },
    vars: { ask_pen: 31 },
    maxHp: 20,
    hp: 20,
    pieces: ['hp_d1_r09', 'hp_ask_ridge', 'hp_myr_pines', 'hp_myr_brook'],
    opened: ['d1_hc'],
    dungeons: { d1: { bossDead: true } },
  },
  /** Before Lindormr's big lock with everything D2 gives: bombs in slot K, the boomerang in L, the big key. */
  d2boss: {
    screen: 'd2_r11',
    tile: [19, 3],
    facing: 'n',
    weapon: 'seax',
    shield: true,
    minute: 10 * 60,
    season: 'autumn',
    policy: 'cycling',
    silver: 70,
    items: { lantern: 1, boomerang: 1, horn: 1, mead_red: 1, purse: 1, bombs: 10 },
    slots: ['bombs', 'boomerang'],
    galdr: ['eldr'],
    flags: { ...MYL_FLAGS, st_d2_entered: true, w_d2_level: 2 },
    vars: { ask_pen: 31 },
    maxHp: 16,
    hp: 16,
    pieces: ['hp_d1_r09'],
    opened: [
      'd1_hc',
      'd2_c_key1',
      'd2_c_key2',
      'd2_c_key3',
      'd2_c_map',
      'd2_c_compass',
      'd2_c_bombs',
      'd2_c_bigkey',
    ],
    dungeons: {
      d1: { bossDead: true },
      d2: {
        bigKey: true,
        map: true,
        compass: true,
        doors: ['d2_lock_a', 'd2_lock_b', 'd2_lock_c', 'd2_sh_r07', 'd2_sh_r07w'],
      },
    },
  },

  /** At the mouth of Rótarhellir, just inside: seax, shield and the lantern. */
  d1: {
    screen: 'd1_r01',
    tile: [19, 18],
    facing: 'n',
    weapon: 'seax',
    shield: true,
    minute: 9 * 60,
    season: 'autumn',
    policy: 'cycling',
    silver: 5,
    ...LANTERN,
    flags: { ...MYR_FLAGS, st_d1_entered: true },
    vars: { ask_pen: 31 },
  },
  /** At the door of Rótvættr's lair with everything D1 gives: the boomerang in slot K, the way open. */
  d1boss: {
    screen: 'd1_r11',
    tile: [19, 3],
    facing: 'n',
    weapon: 'seax',
    shield: true,
    minute: 9 * 60,
    season: 'autumn',
    policy: 'cycling',
    silver: 25,
    items: { lantern: 1, boomerang: 1 },
    slots: ['boomerang', 'lantern'],
    flags: { ...MYR_FLAGS, st_d1_entered: true },
    vars: { ask_pen: 31 },
    opened: ['d1_c_key1', 'd1_c_key2', 'd1_c_map', 'd1_c_compass', 'd1_c_boomerang'],
    dungeons: {
      d1: {
        keys: 1,
        map: true,
        compass: true,
        doors: ['d1_sh_r04', 'd1_sh_r05', 'd1_lock_b', 'd1_sh_r07', 'd1_sh_boss'],
      },
    },
  },
} as const satisfies Record<string, DevPreset>;

export type DevPresetId = keyof typeof DEV_PRESETS;

export const isDevPresetId = (s: string): s is DevPresetId => Object.hasOwn(DEV_PRESETS, s);
