import type { SfxId } from '@content/ids';
import type { SynthParams } from './synth';

/** Placeholder recipes. Real recordings later replace these by the same SfxId. */
export const SFX_BANK = {
  sfx_swing: {
    wave: 'noise',
    freq: 4000,
    freqEnd: 1200,
    attack: 0.005,
    sustain: 0.03,
    release: 0.08,
    volume: 0.35,
  },
  sfx_spin: {
    wave: 'noise',
    freq: 2500,
    freqEnd: 6000,
    attack: 0.01,
    sustain: 0.2,
    release: 0.15,
    volume: 0.35,
  },
  sfx_hit: {
    wave: 'square',
    freq: 220,
    freqEnd: 70,
    attack: 0,
    sustain: 0.03,
    release: 0.09,
    volume: 0.4,
    duty: 0.3,
  },
  sfx_block: {
    wave: 'square',
    freq: 900,
    freqEnd: 700,
    attack: 0,
    sustain: 0.02,
    release: 0.06,
    volume: 0.3,
  },
  sfx_roll: {
    wave: 'noise',
    freq: 900,
    freqEnd: 300,
    attack: 0.02,
    sustain: 0.08,
    release: 0.12,
    volume: 0.25,
  },
  sfx_charge: {
    wave: 'triangle',
    freq: 660,
    freqEnd: 1320,
    attack: 0.01,
    sustain: 0.05,
    release: 0.12,
    volume: 0.3,
  },
  sfx_talk: {
    wave: 'square',
    freq: 520,
    freqEnd: 480,
    attack: 0,
    sustain: 0.015,
    release: 0.02,
    volume: 0.12,
    duty: 0.25,
  },
  sfx_lift: {
    wave: 'triangle',
    freq: 180,
    freqEnd: 360,
    attack: 0.01,
    sustain: 0.04,
    release: 0.06,
    volume: 0.3,
  },
  sfx_throw: {
    wave: 'noise',
    freq: 1800,
    freqEnd: 600,
    attack: 0.01,
    sustain: 0.05,
    release: 0.08,
    volume: 0.25,
  },
  sfx_break: {
    wave: 'noise',
    freq: 3000,
    freqEnd: 400,
    attack: 0,
    sustain: 0.04,
    release: 0.2,
    volume: 0.4,
  },
  sfx_door: {
    wave: 'saw',
    freq: 140,
    freqEnd: 90,
    attack: 0.02,
    sustain: 0.1,
    release: 0.15,
    volume: 0.2,
  },
  sfx_buy: {
    wave: 'square',
    freq: 880,
    freqEnd: 1320,
    attack: 0,
    sustain: 0.05,
    release: 0.1,
    volume: 0.25,
    duty: 0.5,
  },
  sfx_bleat: {
    wave: 'saw',
    freq: 420,
    freqEnd: 360,
    attack: 0.03,
    sustain: 0.18,
    release: 0.12,
    volume: 0.2,
  },
  sfx_caw: {
    wave: 'saw',
    freq: 900,
    freqEnd: 500,
    attack: 0.01,
    sustain: 0.08,
    release: 0.1,
    volume: 0.25,
  },
  sfx_itemget: {
    wave: 'triangle',
    freq: 660,
    freqEnd: 1760,
    attack: 0.01,
    sustain: 0.2,
    release: 0.25,
    volume: 0.3,
  },
  sfx_cut: {
    wave: 'noise',
    freq: 5000,
    freqEnd: 2500,
    attack: 0,
    sustain: 0.02,
    release: 0.05,
    volume: 0.2,
  },
  /** The hero takes a hit: a short falling grunt. */
  sfx_hurt: {
    wave: 'saw',
    freq: 330,
    freqEnd: 150,
    attack: 0,
    sustain: 0.05,
    release: 0.12,
    volume: 0.35,
  },
  /** The hero falls: a long slide down. */
  sfx_die: {
    wave: 'triangle',
    freq: 520,
    freqEnd: 60,
    attack: 0.01,
    sustain: 0.5,
    release: 0.4,
    volume: 0.4,
  },
  /** A beast's warning before it strikes. */
  sfx_growl: {
    wave: 'saw',
    freq: 110,
    freqEnd: 80,
    attack: 0.03,
    sustain: 0.25,
    release: 0.15,
    volume: 0.3,
  },
  /** A long rumble after the lightning flash. */
  sfx_thunder: {
    wave: 'noise',
    freq: 220,
    freqEnd: 40,
    attack: 0.02,
    sustain: 0.6,
    release: 0.9,
    volume: 0.45,
  },
  /** Fire flaring up (a burn). */
  sfx_fire: {
    wave: 'noise',
    freq: 1800,
    freqEnd: 600,
    attack: 0.01,
    sustain: 0.12,
    release: 0.2,
    volume: 0.3,
  },
  /** An enemy vanishing in a puff. */
  sfx_poof: {
    wave: 'noise',
    freq: 700,
    freqEnd: 2600,
    attack: 0.005,
    sustain: 0.05,
    release: 0.15,
    volume: 0.3,
  },
  /** A heart or a coin picked up. */
  sfx_pickup: {
    wave: 'square',
    freq: 880,
    freqEnd: 1320,
    attack: 0,
    sustain: 0.04,
    release: 0.06,
    volume: 0.25,
    duty: 0.25,
  },
  /** A gate or barrier giving way. */
  sfx_gate: {
    wave: 'saw',
    freq: 140,
    freqEnd: 90,
    attack: 0.01,
    sustain: 0.2,
    release: 0.2,
    volume: 0.3,
  },
  /** A chest lid creaking open. */
  sfx_chest: {
    wave: 'saw',
    freq: 180,
    freqEnd: 320,
    attack: 0.02,
    sustain: 0.14,
    release: 0.12,
    volume: 0.25,
  },
  /** Something hidden shows itself: a rising chime. */
  sfx_secret: {
    wave: 'triangle',
    freq: 520,
    freqEnd: 1560,
    attack: 0.01,
    sustain: 0.3,
    release: 0.3,
    volume: 0.3,
  },
  /** A key turning in an old lock. */
  sfx_unlock: {
    wave: 'square',
    freq: 440,
    freqEnd: 660,
    attack: 0,
    sustain: 0.03,
    release: 0.08,
    volume: 0.25,
    duty: 0.4,
  },
  /** Bars dropping shut, or grinding open. */
  sfx_shutter: {
    wave: 'noise',
    freq: 400,
    freqEnd: 120,
    attack: 0,
    sustain: 0.1,
    release: 0.18,
    volume: 0.4,
  },
  /** A switch stone struck alight. */
  sfx_switch: {
    wave: 'triangle',
    freq: 1320,
    freqEnd: 990,
    attack: 0,
    sustain: 0.06,
    release: 0.15,
    volume: 0.3,
  },
  /** A root block scraping a tile along the floor. */
  sfx_push: {
    wave: 'noise',
    freq: 260,
    freqEnd: 180,
    attack: 0.04,
    sustain: 0.18,
    release: 0.1,
    volume: 0.3,
  },
  /** The boomerang leaving the hand: a quick whirr. */
  sfx_boomerang: {
    wave: 'saw',
    freq: 700,
    freqEnd: 900,
    attack: 0.02,
    sustain: 0.12,
    release: 0.1,
    volume: 0.2,
  },
  /** Something dazed: a wobbling ring. */
  sfx_stun: {
    wave: 'triangle',
    freq: 1100,
    freqEnd: 700,
    attack: 0,
    sustain: 0.1,
    release: 0.2,
    volume: 0.3,
  },
  /** A blow landing on a boss's weak point: deeper and longer than a plain hit. */
  sfx_boss_hit: {
    wave: 'square',
    freq: 160,
    freqEnd: 50,
    attack: 0,
    sustain: 0.06,
    release: 0.2,
    volume: 0.45,
    duty: 0.4,
  },
  /** A boss's roar: a long, low, rough bellow. */
  sfx_boss_roar: {
    wave: 'saw',
    freq: 90,
    freqEnd: 55,
    attack: 0.05,
    sustain: 0.6,
    release: 0.4,
    volume: 0.45,
  },
  /** Grinding rock: a troll turns to stone at sunrise. */
  sfx_stone: {
    wave: 'noise',
    freq: 900,
    freqEnd: 120,
    attack: 0.02,
    sustain: 0.35,
    release: 0.3,
    volume: 0.4,
  },
  /** A gust through the trees. */
  sfx_wind: {
    wave: 'noise',
    freq: 500,
    freqEnd: 900,
    attack: 0.4,
    sustain: 0.8,
    release: 0.8,
    volume: 0.2,
  },
  /** The menu cursor moving. */
  sfx_menu_move: {
    wave: 'square',
    freq: 880,
    freqEnd: 880,
    attack: 0,
    sustain: 0.015,
    release: 0.02,
    volume: 0.15,
  },
  /** A menu choice taken. */
  sfx_menu_ok: {
    wave: 'square',
    freq: 660,
    freqEnd: 1320,
    attack: 0,
    sustain: 0.04,
    release: 0.05,
    volume: 0.2,
  },
  /** A save written to a slot: a rising chime. */
  sfx_save: {
    wave: 'sine',
    freq: 520,
    freqEnd: 1040,
    attack: 0.01,
    sustain: 0.25,
    release: 0.35,
    volume: 0.3,
  },
  /** A long swallow from a mead horn. */
  sfx_drink: {
    wave: 'triangle',
    freq: 330,
    freqEnd: 220,
    attack: 0.02,
    sustain: 0.18,
    release: 0.12,
    volume: 0.3,
  },
  /** Eldr sung: a rising roar of flame. */
  sfx_eldr: {
    wave: 'noise',
    freq: 600,
    freqEnd: 2400,
    attack: 0.02,
    sustain: 0.18,
    release: 0.2,
    volume: 0.4,
  },
  /** A galdr without the seiðr for it: a dull puff. */
  sfx_fizzle: {
    wave: 'noise',
    freq: 1200,
    freqEnd: 300,
    attack: 0,
    sustain: 0.05,
    release: 0.12,
    volume: 0.25,
  },
  /** The pack leader's howl: a long rising, falling moan. */
  sfx_howl: {
    wave: 'triangle',
    freq: 330,
    freqEnd: 520,
    attack: 0.12,
    sustain: 0.35,
    release: 0.3,
    volume: 0.3,
  },
  /** The rime raven's shriek: harsh and high. */
  sfx_shriek: {
    wave: 'square',
    freq: 1400,
    freqEnd: 900,
    attack: 0.01,
    sustain: 0.18,
    release: 0.12,
    volume: 0.2,
    duty: 0.2,
  },
  /** The float pulled under: a quick, bright plip. */
  sfx_bite: {
    wave: 'sine',
    freq: 1300,
    freqEnd: 700,
    attack: 0.003,
    sustain: 0.03,
    release: 0.06,
    volume: 0.35,
  },
  /** The reel ratcheting as the line comes in. */
  sfx_reel: {
    wave: 'square',
    freq: 520,
    freqEnd: 480,
    attack: 0.002,
    sustain: 0.1,
    release: 0.04,
    volume: 0.12,
    duty: 0.1,
  },
  /** The line parting: a thin twang. */
  sfx_snap: {
    wave: 'triangle',
    freq: 1800,
    freqEnd: 300,
    attack: 0.002,
    sustain: 0.04,
    release: 0.2,
    volume: 0.3,
  },
  /** Something small hitting the water. */
  sfx_splash: {
    wave: 'noise',
    freq: 2200,
    freqEnd: 600,
    attack: 0.004,
    sustain: 0.06,
    release: 0.18,
    volume: 0.25,
  },
  /** A water-worm spitting: a wet, falling pop. */
  sfx_spit: {
    wave: 'noise',
    freq: 900,
    freqEnd: 250,
    attack: 0.005,
    sustain: 0.05,
    release: 0.1,
    volume: 0.3,
  },
  /** A bomb going off: a deep, falling roar of noise. */
  sfx_bomb: {
    wave: 'noise',
    freq: 700,
    freqEnd: 60,
    attack: 0.003,
    sustain: 0.12,
    release: 0.45,
    volume: 0.5,
  },
  /** A fuse lit: a short hiss. */
  sfx_fuse: {
    wave: 'noise',
    freq: 5200,
    freqEnd: 3800,
    attack: 0.01,
    sustain: 0.08,
    release: 0.08,
    volume: 0.18,
  },
  /** A mill wheel turning: a low wooden groan. */
  sfx_wheel: {
    wave: 'saw',
    freq: 90,
    freqEnd: 70,
    attack: 0.02,
    sustain: 0.18,
    release: 0.15,
    volume: 0.25,
  },
  /** Water rushing through a sluice. */
  sfx_water: {
    wave: 'noise',
    freq: 1400,
    freqEnd: 500,
    attack: 0.08,
    sustain: 0.3,
    release: 0.4,
    volume: 0.22,
  },
  /** A warp stone waking: a rising, ringing hum. */
  sfx_warp: {
    wave: 'sine',
    freq: 220,
    freqEnd: 660,
    attack: 0.05,
    sustain: 0.25,
    release: 0.5,
    volume: 0.3,
  },
  /** The dash thrust: a sharp, rushing hiss. */
  sfx_thrust: {
    wave: 'noise',
    freq: 6000,
    freqEnd: 1800,
    attack: 0.002,
    sustain: 0.06,
    release: 0.1,
    volume: 0.35,
  },
  /** A parry: a bright ring of steel on steel. */
  sfx_parry: {
    wave: 'square',
    freq: 1760,
    freqEnd: 1320,
    attack: 0,
    sustain: 0.04,
    release: 0.25,
    volume: 0.3,
    duty: 0.2,
  },
  /** A bowstring's snap and the arrow's hiss. */
  sfx_bow: {
    wave: 'triangle',
    freq: 520,
    freqEnd: 180,
    attack: 0,
    sustain: 0.03,
    release: 0.12,
    volume: 0.35,
  },
  /** The dead waking: a low, rising moan. */
  sfx_wake: {
    wave: 'saw',
    freq: 70,
    freqEnd: 140,
    attack: 0.1,
    sustain: 0.3,
    release: 0.4,
    volume: 0.28,
  },
  /** A crown's gem shattering: a bright, falling chime. */
  sfx_gem: {
    wave: 'square',
    freq: 2400,
    freqEnd: 900,
    attack: 0,
    sustain: 0.05,
    release: 0.3,
    volume: 0.3,
    duty: 0.25,
  },
  /** A spectral axe whirling through the air. */
  sfx_axe: {
    wave: 'noise',
    freq: 1800,
    freqEnd: 2600,
    attack: 0.02,
    sustain: 0.15,
    release: 0.1,
    volume: 0.25,
  },
  /** Bragð: the blade sings, a bright ringing sweep up through the air. */
  sfx_bragd: {
    wave: 'square',
    freq: 660,
    freqEnd: 1980,
    attack: 0.01,
    sustain: 0.12,
    release: 0.25,
    volume: 0.28,
    duty: 0.3,
  },
  /** Hlíf's ward taking a blow: a soft glassy chime. */
  sfx_ward: {
    wave: 'triangle',
    freq: 1320,
    freqEnd: 990,
    attack: 0,
    sustain: 0.06,
    release: 0.35,
    volume: 0.3,
  },
  /** A seal of the pass flaring: a deep stone hum rising. */
  sfx_seal: {
    wave: 'triangle',
    freq: 110,
    freqEnd: 220,
    attack: 0.05,
    sustain: 0.3,
    release: 0.3,
    volume: 0.35,
  },
  /** The Rime King's breath pouring out over the lowlands: a long rushing wind. */
  sfx_breath: {
    wave: 'noise',
    freq: 900,
    freqEnd: 300,
    attack: 0.4,
    sustain: 1.2,
    release: 1.2,
    volume: 0.3,
  },
} as const satisfies Record<SfxId, SynthParams>;
